import { describe, expect, it } from 'vitest';
import { exercises, diagnosticIds } from '../src/content/exercises';
import { modules } from '../src/content/modules';
import { cases, dialogue } from '../src/content/cases';
import { grade, evidence, reviewQueue } from '../src/domain/assessment';
import { starterModel, referenceModel, tableProjection, validateModel } from '../src/domain/model';
import { initialApi, apiRequest, simulate, scenarios, type ApiRequest } from '../src/domain/simulation';
import { emptyData } from '../src/state/store';
import { parseImport } from '../src/persistence/schema';
import { exportData } from '../src/persistence/db';
const request=(overrides:Partial<ApiRequest>={}):ApiRequest=>({method:'POST',path:'/api/orders',body:'{"productId":"p-1","quantity":1}',identity:'customer-1',key:'k-1',signature:'',...overrides});
describe('authored educational content',()=>{
 it('contains exactly 72 unique substantive items with planned coverage',()=>{expect(exercises).toHaveLength(72);expect(new Set(exercises.map(e=>e.id)).size).toBe(72);expect(modules.map(m=>exercises.filter(e=>e.module===m.id).length)).toEqual([8,6,7,10,7,8,8,6,6,6]);for(const e of exercises){expect(e.prompt.length).toBeGreaterThan(30);expect(e.explanation.length).toBeGreaterThan(55);expect(e.hints.length).toBeGreaterThanOrEqual(2);if(e.grade==='rubric'){expect(e.criteria!.length).toBeGreaterThanOrEqual(3);expect(e.answer).toHaveLength(0)}else{expect(e.options.length).toBeGreaterThanOrEqual(3);expect(e.options.every(o=>o.feedback.length>15)).toBe(true);expect(e.answer.every(a=>e.options.some(o=>o.id===a))).toBe(true)}}});
 it('has thirty substantive lessons and resolvable prerequisites',()=>{expect(modules.flatMap(m=>m.lessons)).toHaveLength(30);for(const m of modules){expect(m.prerequisites.every(p=>modules.some(m=>m.id===p))).toBe(true);for(const l of m.lessons){expect(l.paragraphs.join(' ').length).toBeGreaterThan(350);expect(l.example.length).toBeGreaterThan(80);expect(l.tryIt.length).toBeGreaterThan(40)}}});
 it('reuses a single diagnostic item per module without inflating the count',()=>{expect(diagnosticIds).toHaveLength(10);expect(diagnosticIds.every(id=>exercises.some(e=>e.id===id))).toBe(true);expect(new Set(diagnosticIds.map(id=>id[0])).size).toBe(10)});
 it('provides complete reference sections, changes and delivery dependencies for all three cases',()=>{expect(cases).toHaveLength(3);for(const c of cases){expect(c.brief.join(' ').length).toBeGreaterThan(900);expect(c.requirements.length).toBeGreaterThanOrEqual(5);expect(c.change.length).toBeGreaterThan(100);for(const key of ['Goal','Users','Flow','Screens','Data','System','API','Tests','Delivery','Tradeoffs'])expect(c.reference[key]?.length).toBeGreaterThan(0);expect(c.tasks.every(t=>t.depends.every(id=>c.tasks.some(x=>x.id===id)))).toBe(true)}});
 it('has twelve reachable conversation beats with useful and recoverable branches',()=>{for(const c of cases){const beats=dialogue(c.id);expect(beats).toHaveLength(12);expect(new Set(beats.map(b=>b.role)).size).toBe(2);for(const b of beats){expect(b.choices.some(c=>c.helpful)).toBe(true);expect(b.choices.some(c=>!c.helpful)).toBe(true);expect(b.choices.every(c=>c.reply.length>30)).toBe(true);expect(b.criteria.length).toBeGreaterThan(1)}}});
});
describe('assessment semantics',()=>{
 it('multi-select rejects both missing and extra selections',()=>{const e=exercises.find(e=>e.id==='D4')!;expect(grade(e,e.answer)).toBe(true);expect(grade(e,e.answer.slice(1))).toBe(false);expect(grade(e,[...e.answer,'1'])).toBe(false)});
 it('ordering and matching require positions, not just membership',()=>{for(const id of ['B5','D10']){const e=exercises.find(e=>e.id===id)!;expect(grade(e,e.answer)).toBe(true);expect(grade(e,[...e.answer].reverse())).toBe(false)}});
 it('never awards semantic correctness to prose',()=>{const e=exercises.find(e=>e.id==='J1')!;expect(grade(e,['every keyword'])).toBeNull()});
 it('distinct unassisted evidence is separate from hints and repeated retries',()=>{const base={id:'a',exerciseId:'D1',contentVersion:'1',response:['1'],text:'',grade:'objective' as const,correct:true,criteria:[],confidence:5,hints:0,at:'2026-09-18T00:00:00Z',review:false};expect(evidence([base,{...base,id:'b'},{...base,id:'c',exerciseId:'D2',hints:1}],'D').demonstrated).toBe(1);expect(reviewQueue([{...base,correct:false,review:true},base])).toHaveLength(0)});
});
describe('relationship semantics and projections',()=>{
 it('finds the deliberate one-to-one error and price loss, without rejecting valid keys',()=>{const checks=validateModel(starterModel());expect(checks.find(f=>f.id==='order-lines')!.ok).toBe(false);expect(checks.find(f=>f.id==='price-snapshot')!.ok).toBe(false);expect(checks.filter(f=>f.id.endsWith('key')).every(f=>f.ok)).toBe(true)});
 it('accepts the reference and is independent of edge orientation',()=>{const m=referenceModel();expect(validateModel(m).every(f=>f.ok)).toBe(true);m.relationships=m.relationships.map(r=>({...r,a:r.b,b:r.a,atA:r.atB,atB:r.atA}));expect(validateModel(m).every(f=>f.ok)).toBe(true)});
 it('supports the declared empty-draft alternative',()=>{const m=referenceModel();m.submitted=false;m.relationships[0].atB='0..*';expect(validateModel(m).every(f=>f.ok)).toBe(true);m.submitted=true;expect(validateModel(m).find(f=>f.id==='order-lines')!.ok).toBe(false)});
 it('puts FK on the many side, not unique, and explains the parent minimum limit',()=>{const tables=tableProjection(referenceModel());const line=tables.find(t=>t.name==='OrderLine')!;expect(line.columns).toContain('order_id FOREIGN KEY → Order NOT NULL');expect(line.columns.find(c=>c.startsWith('order_id'))).not.toContain('UNIQUE');expect(tables.find(t=>t.name==='Order')!.notes[0]).toContain('do not enforce')});
 it('projects a many-to-many join and one-to-one uniqueness deliberately',()=>{const m=referenceModel();m.relationships[0].atA='0..*';const join=tableProjection(m).find(t=>t.name==='Order_OrderLine');expect(join?.columns).toHaveLength(2);const one=starterModel();expect(tableProjection(one).find(t=>t.name==='OrderLine')!.columns.some(c=>c.includes('order_id')&&c.includes('UNIQUE'))).toBe(true)});
 it('catches null primary keys and broken references',()=>{const m=referenceModel();m.entities[0].attributes[0].nullable=true;m.relationships[0].a='missing';expect(validateModel(m).some(f=>f.id==='orderkey'&&!f.ok)).toBe(true);expect(validateModel(m).some(f=>f.title==='Broken relationship')).toBe(true)});
});
describe('API and realistic failure fixtures',()=>{
 it('creates once for repeated intent and rejects conflicting reuse',()=>{const first=apiRequest(initialApi(),request());const repeat=apiRequest(first.state,request());expect(first.status).toBe(201);expect(repeat.status).toBe(200);expect(repeat.state.stock).toBe(2);expect(repeat.state.orders).toHaveLength(2);expect(apiRequest(repeat.state,request({body:'{"productId":"p-1","quantity":2}'})).status).toBe(409)});
 it('protects object access with two authenticated identities',()=>{const state=initialApi();expect(apiRequest(state,request({method:'GET',path:'/api/orders/o-1',body:'',identity:'customer-1'})).status).toBe(200);expect(apiRequest(state,request({method:'GET',path:'/api/orders/o-1',body:'',identity:'customer-2'})).status).toBe(404);expect(apiRequest(state,request({method:'GET',path:'/api/orders/o-1',body:'',identity:'anonymous'})).status).toBe(401)});
 it('preserves historical prices after a staff price change',()=>{const changed=apiRequest(initialApi(),request({method:'PATCH',path:'/api/products/p-1',identity:'staff',body:'{"priceMinor":60000}'}));expect(changed.state.price).toBe(60000);const result=apiRequest(changed.state,request({method:'GET',path:'/api/orders/o-1',body:''}));expect(result.body).toMatchObject({unitPriceMinor:50000,totalMinor:100000})});
 it('rejects bad JSON, field values and untrusted staff mutations',()=>{expect(apiRequest(initialApi(),request({body:'{'})).status).toBe(400);for(const n of [0,11,1.5])expect(apiRequest(initialApi(),request({body:JSON.stringify({productId:'p-1',quantity:n})})).status).toBe(422);expect(apiRequest(initialApi(),request({method:'PATCH',path:'/api/products/p-1',body:'{"priceMinor":1}'})).status).toBe(403)});
 it('prevents overselling and uses trusted prices',()=>{let state=initialApi();state.stock=1;let a=apiRequest(state,request({body:'{"productId":"p-1","quantity":1,"unitPriceMinor":1}'}));expect(a.state.orders.at(-1)?.unitPriceMinor).toBe(50000);expect(apiRequest(a.state,request({identity:'customer-2'})).status).toBe(409)});
 it('requires fixture verification, deduplicates events and does not downgrade paid',()=>{const req=request({path:'/api/webhooks/payment',body:'{"eventId":"e1","orderId":"o-1","status":"failed"}',signature:'fixture-valid'});expect(apiRequest(initialApi(),{...req,signature:''}).status).toBe(401);const a=apiRequest(initialApi(),req);expect(a.state.orders[0].status).toBe('paid');expect(apiRequest(a.state,req).state.events).toEqual(['e1'])});
 it('filters and validates pagination',()=>{expect(apiRequest(initialApi(),request({method:'GET',path:'/api/products?page=0',body:''})).status).toBe(422);expect(apiRequest(initialApi(),request({method:'GET',path:'/api/products?category=unknown',body:''})).body).toMatchObject({items:[]})});
 it('keeps external truth separate from local knowledge during timeout and rollback',()=>{const timeout=simulate('timeout-after').find(f=>f.title.includes('Lose'))!;expect(timeout.db).toContain('unknown');expect(timeout.provider).toContain('succeeded');const fail=simulate('local-failure').find(f=>f.transaction.includes('ROLLBACK'))!;expect(fail.provider).toContain('Charges: 1');expect(fail.db).toContain('pending')});
 it('every scenario has an explicit boundary and complete state frames',()=>{for(const [id] of scenarios){const frames=simulate(id);expect(frames.length).toBeGreaterThan(3);expect(frames.some(f=>f.boundary)).toBe(true);expect(frames.every(f=>f.db&&f.provider&&f.user&&f.transaction)).toBe(true)}});
});
describe('versioned interchange',()=>{
 it('round trips complete progress and model snapshots',()=>{const d=emptyData();d.documents.example=referenceModel();d.notes.intro='Min introduktion';expect(parseImport(exportData(d))).toEqual(d)});
 it('rejects a future schema or malformed JSON without touching a caller’s state',()=>{const original=emptyData();const snapshot=structuredClone(original);const data=JSON.parse(exportData(original));data.schemaVersion=42;expect(()=>parseImport(JSON.stringify(data))).toThrow();expect(()=>parseImport('{')).toThrow();expect(original).toEqual(snapshot)});
 it('rejects broken model references and unknown case domains',()=>{const d=emptyData();d.documents.x=referenceModel();d.documents.x.relationships[0].a='missing';expect(()=>parseImport(exportData(d))).toThrow('broken relationships')});
 it('rejects an interview without its case',()=>{const d=emptyData();d.interviews.x={id:'x',caseAttemptId:'missing',beat:0,turns:[],done:false,assisted:false,summary:'',selfReview:[],startedAt:'today'};expect(()=>parseImport(exportData(d))).toThrow('missing case')});
});
