import 'fake-indexeddb/auto';
import { afterEach, describe, expect, it } from 'vitest';
import { db, readData, writeData } from '../src/persistence/db';
import { createCase, changeRequirement, useLab, emptyData, flush, canUndo, canRedo, referenceLocked } from '../src/state/store';
import { starterModel, referenceModel } from '../src/domain/model';
afterEach(async()=>{await flush();await db.profiles.clear();await useLab.getState().replace(emptyData());});
describe('local persistence, undo and requirement changes',()=>{
 it('saves and reads a versioned complete profile',async()=>{const d=emptyData();d.revision=1;d.notes.intro='Hello';await writeData(d,0);expect((await readData())?.notes.intro).toBe('Hello')});
 it('rejects stale writes from another tab atomically',async()=>{await useLab.getState().replace(emptyData());const current=(await readData())!;const a={...current,revision:current.revision+1};await writeData(a,current.revision);await expect(writeData({...a,revision:a.revision+1},current.revision)).rejects.toThrow('Another tab');expect((await readData())?.revision).toBe(a.revision)});
 it('reports storage errors honestly and keeps the in-memory work available',async()=>{await useLab.getState().replace(emptyData());const data=useLab.getState().data;await db.profiles.put({id:'main',data:{...data,revision:data.revision+500}});useLab.getState().mutate(d=>{d.notes.saved='Keep me'});await flush();expect(useLab.getState().status).toBe('error');expect(useLab.getState().data.notes.saved).toBe('Keep me')});
 it('preserves previous requirements, artefacts and stale trace evidence on change',async()=>{const id=createCase('webshop','guided');useLab.getState().mutate(d=>{d.cases[id].traces.push({id:'t',requirement:'R3',type:'test',artifact:'tests',note:'price snapshot',reviewedRevision:1});d.documents['case:'+id+':model']=referenceModel()});changeRequirement(id);const d=useLab.getState().data;expect(d.cases[id].requirements.find(r=>r.id==='R3')?.revision).toBe(2);expect(d.cases[id].traces[0].reviewedRevision).toBe(1);expect(d.documents['case:'+id+':model']).toBeDefined();changeRequirement(id);expect(useLab.getState().data.cases[id].revision).toBe(2)});
 it('supports undo, redo and a new edit clears redo',()=>{useLab.getState().doc('x',starterModel());useLab.getState().doc('x',referenceModel());expect(canUndo('x')).toBe(true);useLab.getState().undo('x');expect((useLab.getState().data.documents.x as ReturnType<typeof starterModel>).relationships[0].atB).toBe('1');expect(canRedo('x')).toBe(true);useLab.getState().redo('x');expect((useLab.getState().data.documents.x as ReturnType<typeof starterModel>).relationships[0].atB).toBe('1..*');useLab.getState().undo('x');useLab.getState().doc('x',starterModel(true));expect(canRedo('x')).toBe(false)});
 it('protects references across routes until the independent case ends',()=>{const id=createCase('webshop','independent');expect(referenceLocked('webshop')).toBe(true);expect(referenceLocked('rental')).toBe(false);useLab.getState().mutate(d=>{d.cases[id].ended=true});expect(referenceLocked('webshop')).toBe(false)});
});
