import { useEffect, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ChevronDown, RotateCcw, Undo2, Redo2, BookmarkPlus, Check, Lightbulb, Play, Pause } from 'lucide-react';
import { useLab, canUndo, canRedo } from '../state/store';
import { uid } from '../domain/model';
import type { Document, Finding } from '../domain/types';
export function PageHead({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){return <header className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p className="lede">{description}</p>}</div>{action}</header>}
export function LinkButton({to,children,secondary=false}:{to:string;children:ReactNode;secondary?:boolean}){return <Link className={`button ${secondary?'secondary':''}`} to={to}>{children}<ArrowRight size={17}/></Link>}
export function Badge({children,tone=''}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function Disclosure({title,children,open=false}:{title:string;children:ReactNode;open?:boolean}){return <details className="disclosure" open={open||undefined}><summary>{title}<ChevronDown size={16}/></summary><div>{children}</div></details>}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="empty"><div className="empty-mark">↗</div><h3>{title}</h3><p>{children}</p></div>}
export function Timer({seconds=90}:{seconds?:number}){const [remaining,setRemaining]=useState(seconds);const [running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const t=setInterval(()=>setRemaining(n=>{if(n<=1){setRunning(false);return 0;}return n-1;}),1000);return()=>clearInterval(t)},[running]);return <div className="timer"><span aria-label={`${remaining} seconds remaining`}>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</span><button className="icon-button" aria-label={running?'Pause timer':'Start timer'} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>}</button><button className="icon-button" aria-label="Reset timer" onClick={()=>{setRunning(false);setRemaining(seconds)}}><RotateCcw size={16}/></button><small>Optional · no time score</small></div>}
export function Findings({items}:{items:Finding[]}){return <div className="findings" aria-live="polite">{items.map(f=><div key={f.id} className={`finding ${f.ok?'good':'attention'}`}><div className="finding-icon">{f.ok?<Check size={17}/>:<Lightbulb size={17}/>}</div><div><div className="eyebrow">{f.kind==='objective'?'Structural check':f.kind==='scenario'?'Declared scenario check':'Self-review'}</div><h4>{f.title}</h4><p>{f.why}</p>{!f.ok&&<p className="hint"><strong>Try this:</strong> {f.hint}</p>}</div></div>)}</div>}
export function useDocument<T extends Document>(id:string,initial:()=>T){const existing=useLab(s=>s.data.documents[id]);const [fallback]=useState(initial);useEffect(()=>{if(!useLab.getState().data.documents[id])useLab.getState().mutate(d=>{d.documents[id]=structuredClone(fallback)})},[id,fallback]);const doc=(existing??fallback) as T;const change=(fn:(draft:T)=>void)=>{const next=structuredClone(doc);fn(next);useLab.getState().doc(id,next)};return {doc,change};}
export function HistoryBar({id}:{id:string}){useLab(s=>s.historyTick);const checkpoints=useLab(s=>s.data.checkpoints[id])??[];const [name,setName]=useState('');const [selected,setSelected]=useState('');const [message,setMessage]=useState('');return <div className="history-bar"><button className="small" disabled={!canUndo(id)} onClick={()=>useLab.getState().undo(id)}><Undo2 size={15}/>Undo</button><button className="small" disabled={!canRedo(id)} onClick={()=>useLab.getState().redo(id)}><Redo2 size={15}/>Redo</button><input aria-label="Checkpoint name" placeholder="Name this attempt…" value={name} onChange={e=>setName(e.target.value)}/><button className="small" disabled={!name.trim()} onClick={()=>{useLab.getState().mutate(d=>{const list=d.checkpoints[id]??[];d.checkpoints[id]=[...list.slice(-99),{id:uid(),title:name.trim(),at:new Date().toISOString(),doc:structuredClone(d.documents[id])}]});setName('');setMessage('Checkpoint saved')}}><BookmarkPlus size={15}/>Save attempt</button>{checkpoints.length>0&&<><select aria-label="Saved attempts" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Saved attempts ({checkpoints.length})</option>{checkpoints.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button className="small" disabled={!selected} onClick={()=>{const c=checkpoints.find(c=>c.id===selected);if(c){useLab.getState().doc(id,structuredClone(c.doc));setMessage('Checkpoint restored. Undo returns to your previous work.')}}}>Restore</button></>}<span role="status" className="muted small-text">{message}</span></div>}
export function Rubric({criteria,value,onChange}:{criteria:string[];value:string[];onChange:(v:string[])=>void}){return <div className="rubric"><div className="eyebrow">Your judgment · not machine graded</div>{criteria.map((c,i)=><label className="check-row" key={c}><input type="checkbox" checked={value.includes(String(i))} onChange={e=>onChange(e.target.checked?[...value,String(i)]:value.filter(v=>v!==String(i)))}/><span>{c}</span></label>)}</div>}
