import { z } from 'zod';
const str=z.string().max(100000),id=z.string().min(1).max(200),ids=z.array(id).max(10000),record=<T extends z.ZodType>(v:T)=>z.record(z.string(),v);
const attr=z.object({id,name:str,type:str,key:z.boolean(),nullable:z.boolean(),unique:z.boolean()});
const mult=z.enum(['0..1','1','0..*','1..*']);
const model=z.object({kind:z.literal('model'),entities:z.array(z.object({id,name:str,concept:str,attributes:z.array(attr).max(100),x:z.number().finite(),y:z.number().finite()})).max(200),relationships:z.array(z.object({id,a:id,b:id,atA:mult,atB:mult,label:str})).max(1000),assumptions:str,notation:z.enum(['uml','er']),submitted:z.boolean()});
const wire=z.object({kind:z.literal('wire'),screens:z.array(z.object({id,name:str,components:z.array(z.object({id,type:str,label:str,span:z.number().min(1).max(12),required:z.boolean(),target:str,state:str})).max(200)})).max(50),rationale:str,checks:ids});
const architecture=z.object({kind:z.literal('architecture'),components:z.array(z.object({id,name:str,role:str,x:z.number().finite(),y:z.number().finite()})).max(200),connections:z.array(z.object({id,from:id,to:id})).max(1000),rationale:str,scenario:str});
export const documentSchema=z.discriminatedUnion('kind',[model,wire,architecture]);
const caseSchema=z.object({id,caseId:id,title:str,mode:z.enum(['guided','independent']),revision:z.number().int().nonnegative(),requirements:z.array(z.object({id,text:str,category:z.enum(['fact','assumption','constraint','question']),priority:str,revision:z.number().int().nonnegative()})),traces:z.array(z.object({id,requirement:id,type:str,artifact:str,note:str,reviewedRevision:z.number().int().nonnegative()})),notes:record(str),delivery:ids,deferred:ids,deadline:z.number().min(1).max(100),changed:z.boolean(),ended:z.boolean(),referenceSeen:z.boolean(),checks:ids});
export const learningSchema=z.object({schemaVersion:z.literal(1),contentVersion:str,revision:z.number().int().nonnegative(),updatedAt:str,completed:ids,attempts:z.array(z.object({id,exerciseId:id,contentVersion:str,response:ids,text:str,grade:z.enum(['objective','scenario','rubric']),correct:z.boolean().nullable(),criteria:ids,confidence:z.number().min(1).max(5),hints:z.number().int().nonnegative(),at:str,review:z.boolean(),reviewedAt:str.optional()})).max(20000),documents:record(documentSchema),checkpoints:record(z.array(z.object({id,title:str,at:str,doc:documentSchema})).max(100)),cases:record(caseSchema),interviews:record(z.object({id,caseAttemptId:id,beat:z.number().int().min(0).max(12),turns:z.array(z.object({beat:z.number().int().min(0).max(11),choice:z.number().int().min(0).max(2),response:str,feedback:str,helpful:z.boolean()})).max(100),done:z.boolean(),assisted:z.boolean(),summary:str,selfReview:ids,startedAt:str})),notes:record(str),resume:str,diagnosticIndex:z.number().int().min(0).max(10),diagnosticDone:z.boolean(),path:str,exposed:ids});
export const exportSchema=z.object({format:z.literal('netcompany-interview-lab'),schemaVersion:z.literal(1),exportedAt:str,data:learningSchema});
export function parseImport(text:string){if(text.length>20_000_000)throw new Error('The file exceeds the 20 MB import limit.');const parsed=exportSchema.parse(JSON.parse(text));const d=parsed.data;for(const [key,c] of Object.entries(d.cases)){if(c.id!==key||!['webshop','courses','rental'].includes(c.caseId))throw new Error('Invalid case identity.');const req=new Set(c.requirements.map(r=>r.id));if(req.size!==c.requirements.length||c.traces.some(t=>!req.has(t.requirement)))throw new Error('A requirement link is broken.');}for(const i of Object.values(d.interviews))if(!d.cases[i.caseAttemptId])throw new Error('An interview references a missing case.');for(const doc of Object.values(d.documents)){if(doc.kind==='model'){const keys=new Set(doc.entities.map(e=>e.id));if(keys.size!==doc.entities.length||doc.relationships.some(r=>!keys.has(r.a)||!keys.has(r.b)))throw new Error('A model contains duplicate entities or broken relationships.');}if(doc.kind==='wire'){const keys=new Set(doc.screens.map(s=>s.id));if(doc.screens.some(s=>s.components.some(c=>c.target&&!keys.has(c.target))))throw new Error('A wireframe transition points to a missing screen.');}if(doc.kind==='architecture'){const keys=new Set(doc.components.map(c=>c.id));if(doc.connections.some(c=>!keys.has(c.from)||!keys.has(c.to)))throw new Error('An architecture connection is broken.');}}return d;}
