import {useState,useRef,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,Network,Grid2X2,Minus,Plus,Scan,MousePointer2,GitBranch,X,BookOpen} from 'lucide-react';
import {papers,relationships,focuses,concepts,paperById,inventory} from './data';
import {Citation,Eyebrow,PaperGlyph,useUI} from './ui';
import type {Relationship} from './types';
export default function Atlas(){
 const [focus,setFocus]=useState('all'),[view,setView]=useState(()=>window.innerWidth<=700?'grid':'map'),[hover,setHover]=useState<string|null>(null),[edge,setEdge]=useState<Relationship|null>(null),[scale,setScale]=useState(.85);const box=useRef<HTMLDivElement>(null);const current=focuses.find(f=>f.id===focus)!;const {open}=useUI();
 const fit=()=>{if(box.current)setScale(Math.max(.72,Math.min(1,(box.current.clientWidth-20)/1200)))};useEffect(()=>{fit();const o=new ResizeObserver(fit);if(box.current)o.observe(box.current);return()=>o.disconnect()},[view]);
 const active=(id:string)=>current.ids.includes(id);const edgeActive=(r:Relationship)=>active(r.a)&&active(r.b)&&(!hover||r.a===hover||r.b===hover);
 const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 return <><div className="page-intro atlas-intro"><div><Eyebrow><span className="live-dot"/> Your research, connected</Eyebrow><h1>From papers<br/>to <em>understanding.</em></h1><p>Find the shared ideas. Follow the methods.<br/>Build a mental model that stays with you.</p></div><div className="collection-stat"><span className="stat-number">{String(papers.length).padStart(2,'0')}</span><div>research papers<br/><span>{concepts.length} concepts · {relationships.length} connections</span></div><div className="verified-tag"><BookOpen size={13}/> Grounded in your PDFs</div></div></div>
 <div className="atlas-toolbar"><div className="focus-tabs" aria-label="Focus the atlas">{focuses.map(f=><button key={f.id} className={focus===f.id?'active':''} aria-pressed={focus===f.id} onClick={()=>{setFocus(f.id);setHover(null);setEdge(null)}}>{f.name}</button>)}</div><div className="view-toggle"><button aria-label="Constellation view" aria-pressed={view==='map'} className={view==='map'?'active':''} onClick={()=>setView('map')}><Network size={17}/></button><button aria-label="Paper card view" aria-pressed={view==='grid'} className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button></div></div>
 <div className="focus-description"><span className="tiny-label">{focus==='all'?'THE COLLECTION':current.name.toUpperCase()}</span><p>{current.intro}</p><span>{current.ids.length} papers</span></div>
 {view==='map'?<div className="graph-shell"><div className="graph-viewport" ref={box} onPointerDown={e=>{if((e.target as HTMLElement).closest('a,button'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current){e.currentTarget.scrollLeft=drag.current.left-(e.clientX-drag.current.x);e.currentTarget.scrollTop=drag.current.top-(e.clientY-drag.current.y)}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><div className="graph-size" style={{width:1200*scale,height:870*scale}}><div className="graph-canvas" style={{transform:`scale(${scale})`}}><div className="map-region region-one"><span>01 / GENERATIVE SYSTEMS</span><p>Represent · transport · sample</p></div><div className="map-region region-two"><span>02 / MEDICAL INTELLIGENCE</span><p>Reconstruct · forecast · segment</p></div><svg className="connections" viewBox="0 0 1200 870" aria-label="Labelled relationships between papers">{relationships.map((r,i)=>{const a=paperById(r.a).position,b=paperById(r.b).position;const ax=a[0]+128,ay=a[1]+80,bx=b[0]+128,by=b[1]+80;let path=`M${ax},${ay} C${ax},${(ay+by)/2} ${bx},${(ay+by)/2} ${bx},${by}`;let lx=(ax+bx)/2,ly=(ay+by)/2;if(ay===by){path=`M${ax},${ay} L${bx},${by}`;ly=ay-3}if(r.a==='sphere'&&r.b==='wcc4ms'){path=`M${ax},${ay} C${ax+130},${ay+320} ${bx+200},${by+150} ${bx},${by}`;lx=824;ly=835}if(r.a==='drift'&&r.b==='pdf'){path=`M${ax},${ay} C${ax},${ay+220} ${bx},${by-220} ${bx},${by}`;lx+=2;ly+=15}if(r.a==='sphere'&&r.b==='c2p'){lx+=18;ly+=20}return <g key={i} className={`connection ${edgeActive(r)?'':'muted'} ${hover&&(r.a===hover||r.b===hover)?'highlight':''}`}><path d={path}/><foreignObject x={lx-105} y={ly-12} width="210" height="32"><button className="edge-label" onClick={()=>setEdge(r)} tabIndex={edgeActive(r)?0:-1} aria-label={`Connection: ${paperById(r.a).short} and ${paperById(r.b).short}, ${r.label}`}>{r.label}</button></foreignObject></g>})}</svg>
 {papers.map(p=><a key={p.id} href={`#/paper/${p.id}`} className={`map-paper ${active(p.id)?'':'dimmed'} ${hover===p.id?'hovered':''}`} style={{left:p.position[0],top:p.position[1],'--paper-color':p.color} as React.CSSProperties} onMouseEnter={()=>setHover(p.id)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(p.id)} onBlur={()=>setHover(null)}><div className="map-card-top"><span className="paper-number">{p.number}</span><PaperGlyph paper={p}/><ArrowUpRight size={17}/></div><h3>{p.short}</h3><p className="map-task">{p.task}</p><div className="map-card-bottom"><i/><span>{p.category}</span></div>{hover===p.id&&<div className="paper-popover"><span className="tiny-label">{p.short} · {p.category}</span><h4>{p.title}</h4><p>{p.sentence.text}</p><div>{p.concepts.slice(0,4).map(id=><span key={id}>{concepts.find(c=>c.id===id)?.name}</span>)}</div><small>Open the guided walkthrough <ArrowRight size={13}/></small></div>}</a>)}
 <div className="map-note"><GitBranch size={20}/><h3>Shared ideas.<br/>Different mechanisms.</h3><p>Click a connection to see what the papers share—and where they diverge.</p><a href="#/concepts">Explore the concepts <ArrowRight size={14}/></a></div></div></div></div><div className="graph-bottom"><span><MousePointer2 size={14}/> Hover to preview · click to explore · drag background to pan</span><div className="graph-legend"><i className="lime"/> Generative methods <i className="teal"/> Medical methods</div><div className="zoom-controls"><button aria-label="Zoom out atlas" onClick={()=>setScale(s=>Math.max(.35,s-.1))}><Minus size={16}/></button><span>{Math.round(scale*100)}%</span><button aria-label="Zoom in atlas" onClick={()=>setScale(s=>Math.min(1.5,s+.1))}><Plus size={16}/></button><button aria-label="Fit atlas to view" onClick={fit}><Scan size={16}/></button></div></div>{edge&&<div className="edge-inspector"><button className="icon-button" aria-label="Close connection" onClick={()=>setEdge(null)}><X size={17}/></button><Eyebrow>Connection · editorial synthesis</Eyebrow><h3>{paperById(edge.a).short} <span>↔</span> {paperById(edge.b).short}</h3><p>{edge.reason}</p><div>{edge.sources.map(s=><Citation key={s.paper} paper={s.paper} source={s}/>)}</div></div>}</div>:<div className="paper-grid">{papers.filter(p=>active(p.id)).map(p=><article className="paper-tile" key={p.id} style={{'--paper-color':p.color} as React.CSSProperties}><div className="tile-top"><span className="paper-number">{p.number}</span><PaperGlyph paper={p}/></div><span className="tiny-label">{p.category}</span><h2><a href={`#/paper/${p.id}`}>{p.short}<ArrowUpRight size={20}/></a></h2><p>{p.sentence.text}</p><Citation paper={p.id} source={p.sentence.source}/><a className="text-link" href={`#/paper/${p.id}`}>Understand the method <ArrowRight size={15}/></a></article>)}</div>}
 <div className="home-footer"><div><Eyebrow>A good place to start</Eyebrow><h3>Same word. Different meaning.</h3><p>“Sampling”, “frequency”, and “efficiency” each mean several things in this collection.</p></div><a className="button primary" href="#/concepts">Untangle the concepts <ArrowUpRight size={17}/></a></div>
 <div className="provenance-line"><BookOpen size={13}/><span>{inventory.length} PDFs discovered · physical PDF page citations · explanations reviewed against the local source files</span><button onClick={()=>open({type:'source',paper:'paraflow',source:{page:1,label:'Submission header'}})}>Collection name ≠ venue</button></div>
 {inventory.some(i=>!i.curated)&&<div className="notice">Additional PDFs discovered: {inventory.filter(i=>!i.curated).map(i=>i.filename).join(', ')}. These await source review before educational summaries are added.</div>}
 </>
}
