import {useState,useEffect,useRef} from 'react';
import * as pdfjs from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {ChevronLeft,ChevronRight,ExternalLink,ZoomIn,ZoomOut,LoaderCircle} from 'lucide-react';
import {asset,inventory,paperById} from './data';
import type {Source} from './types';
pdfjs.GlobalWorkerOptions.workerSrc=worker;
export default function PdfViewer({paper,source}:{paper:string;source:Source}){
 const [doc,setDoc]=useState<pdfjs.PDFDocumentProxy|null>(null),[page,setPage]=useState(source.page),[zoom,setZoom]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(true),[text,setText]=useState(''),[width,setWidth]=useState(760);
 const canvas=useRef<HTMLCanvasElement>(null),container=useRef<HTMLDivElement>(null);const meta=inventory.find(i=>i.id===paper)!;const url=asset(meta.pdf);
 useEffect(()=>{setPage(source.page)},[source]);
 useEffect(()=>{setDoc(null);setError('');setBusy(true);let active=true;const task=pdfjs.getDocument({url});task.promise.then(d=>{if(active)setDoc(d)}).catch(e=>{if(active){setError(String(e));setBusy(false)}});return()=>{active=false;void task.destroy()}},[url]);
 useEffect(()=>{const el=container.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setWidth(Math.max(280,entry.contentRect.width-36)));observer.observe(el);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!doc||!canvas.current)return;let active=true;let render:pdfjs.RenderTask|undefined;setBusy(true);setError('');doc.getPage(page).then(async p=>{if(!active||!canvas.current)return;const viewport=p.getViewport({scale:Math.min(width,920)/p.getViewport({scale:1}).width*zoom});const ratio=Math.min(window.devicePixelRatio||1,2);const el=canvas.current;el.width=viewport.width*ratio;el.height=viewport.height*ratio;el.style.width=`${viewport.width}px`;el.style.height=`${viewport.height}px`;render=p.render({canvas:el,viewport,transform:[ratio,0,0,ratio,0,0]});await render.promise;if(active)setBusy(false);const content=await p.getTextContent();if(active)setText(content.items.map(item=>'str'in item?item.str:'').join(' '))}).catch(e=>{if(active&&e?.name!=='RenderingCancelledException'){setError(String(e));setBusy(false)}});return()=>{active=false;render?.cancel()}},[doc,page,zoom,width]);
 return <div className="pdf-viewer"><div className="pdf-toolbar"><div className="button-group"><button className="icon-button" disabled={page<=1} aria-label="Previous PDF page" onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><label>Page <input aria-label="PDF page" type="number" min="1" max={meta.pages} value={page} onChange={e=>setPage(Math.max(1,Math.min(meta.pages,Number(e.target.value)||1)))}/> / {meta.pages}</label><button className="icon-button" disabled={page>=meta.pages} aria-label="Next PDF page" onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div><div className="button-group"><button className="icon-button" aria-label="Zoom out PDF" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,z-.2))}><ZoomOut size={17}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in PDF" disabled={zoom>=2.4} onClick={()=>setZoom(z=>Math.min(2.4,z+.2))}><ZoomIn size={17}/></button><a className="button small-button" href={`${url}#page=${page}`} target="_blank" rel="noreferrer">Original PDF <ExternalLink size={14}/></a></div></div><div className="pdf-location">{paperById(paper).short} · {source.label} <span>Physical PDF pages; printed page numbers may differ.</span></div><div className="pdf-canvas-wrap" ref={container}>{busy&&<div className="loading"><LoaderCircle size={20} className="spin"/> Rendering source page…</div>}{error&&<div role="alert" className="notice">Unable to render: {error}. <a href={`${url}#page=${page}`} target="_blank" rel="noreferrer">Open the original PDF</a>.</div>}<canvas ref={canvas} aria-label={`${paperById(paper).short}, original PDF page ${page}`}/><details className="pdf-transcript"><summary>Accessible extracted page text</summary><p>{text||'Text loading…'}</p></details></div></div>
}
