import {createContext,useContext,useEffect,useRef,type ReactNode} from 'react';
import {ArrowUpRight,BookOpen,X,Maximize2,ZoomIn,ZoomOut} from 'lucide-react';
import {asset,paperById,concepts} from './data';
import type {Paper,Source,Claim,Figure} from './types';
export type Overlay = {type:'source';paper:string;source:Source}|{type:'concept';id:string}|{type:'figure';figure:Figure}|{type:'search'}|null;
export const UIContext=createContext<{open:(value:Overlay)=>void}>({open:()=>{}});
export const useUI=()=>useContext(UIContext);
export function Citation({paper,source}:{paper:string;source:Source}){const {open}=useUI();return <button className="citation" onClick={()=>open({type:'source',paper,source})} title={`Open ${paperById(paper)?.short}, PDF page ${source.page}, ${source.label}`}><BookOpen size={11}/>{paperById(paper)?.short} · p. {source.page} · {source.label}<ArrowUpRight size={11}/></button>}
export function Sourced({paper,value,className=''}:{paper:string;value:Claim;className?:string}){return <div className={`sourced ${className}`}>{value.kind!=='Paper evidence'&&<span className="evidence-label">{value.kind}</span>}<p>{value.text}</p><Citation paper={paper} source={value.source}/></div>}
export function ConceptChips({ids}:{ids:string[]}){const{open}=useUI();return <div className="chips">{ids.map(id=>{const c=concepts.find(c=>c.id===id);return c&&<button className="chip" key={id} onClick={()=>open({type:'concept',id})}>{c.name}<span>+</span></button>})}</div>}
export function Eyebrow({children}:{children:ReactNode}){return <div className="eyebrow">{children}</div>}
export function SectionHeading({number,title,description}:{number:string;title:string;description?:string}){return <div className="section-heading"><span className="section-number">{number}</span><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></div>}
export function FigureCard({figure,compact=false}:{figure:Figure;compact?:boolean}){const{open}=useUI();return <figure className={`figure-card ${compact?'compact':''}`}><button className="figure-image" onClick={()=>open({type:'figure',figure})} aria-label={`Enlarge ${paperById(figure.paper).short} ${figure.figure}`}><img src={asset(figure.file)} alt={`${figure.figure}: ${figure.purpose}`} loading="lazy"/><span className="zoom-badge"><Maximize2 size={14}/> Inspect original</span></button><figcaption><div className="figure-title"><span>{figure.figure}</span><span>PDF p. {figure.page}</span></div><h3>{figure.purpose}</h3>{!compact&&<><p><b>Look for</b> {figure.look}</p><p><b>Take away</b> {figure.conclusion}</p><details><summary>Original caption & provenance</summary><p>{figure.caption}</p><p className="small">{figure.sourcePdf} · physical PDF page {figure.page} · {figure.dpi} DPI render</p><a className="text-link" href={asset(figure.vector)} target="_blank" rel="noreferrer">Open vector-preserving crop <ArrowUpRight size={13}/></a></details></>}<Citation paper={figure.paper} source={{page:figure.page,label:figure.figure}}/></figcaption></figure>}
export function Modal({children,title,onClose,wide=false}:{children:ReactNode;title:string;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;useEffect(()=>{const prev=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('button,input,a')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current()}if(e.key==='Tab'){const items=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),[href],input,select,textarea,[tabindex="0"]')||[]).filter(el=>el.getClientRects().length);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);prev?.focus()}},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`modal ${wide?'wide':''}`} ref={ref} role="dialog" aria-modal="true" aria-label={title}><div className="modal-heading"><div><Eyebrow>Research Atlas</Eyebrow><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></div>{children}</div></div>}
export function PaperGlyph({paper}:{paper:Paper}){return <svg className="paper-glyph" viewBox="0 0 112 40" fill="none" aria-hidden="true" style={{color:paper.color}}>{paper.id==='debat'||paper.id==='wcc4ms'?<><path d="M2 20H24L42 7H69L87 20H110M24 20L42 33H69L87 20" stroke="currentColor" opacity=".5"/><path d="M43 8Q47 0 51 8T59 8T67 8M43 32L47 25L51 37L55 25L59 37L63 25L67 32" stroke="currentColor"/><rect x="4" y="13" width="13" height="14" rx="3" fill="currentColor" opacity=".3"/><rect x="96" y="13" width="13" height="14" rx="3" fill="currentColor" opacity=".7"/></>:paper.id==='paraflow'?<>{[7,20,33].map(y=><g key={y}><path d={`M5 ${y}H107`} stroke="currentColor" opacity=".25"/>{[12,42,72,102].map(x=><circle key={x} cx={x} cy={y} r="3" fill="currentColor" opacity={x/120}/>)}</g>)}</>:paper.id==='drift'||paper.id==='pdf'?<><path d="M5 30C30 36 36 3 65 9S90 24 107 6" stroke="currentColor" opacity=".3" strokeDasharray="3 4"/><path d="M5 30C39 30 59 15 107 6" stroke="currentColor" strokeWidth="1.7"/>{[[5,30],[40,25],[74,13],[107,6]].map(([x,y])=><circle key={x} cx={x} cy={y} r="3" fill="currentColor"/>)}</>:<><path d="M10 8H35L55 20L76 8H103M10 32H35L55 20L76 32H103" stroke="currentColor" opacity=".45"/><rect x="43" y="8" width="25" height="25" rx="6" fill="currentColor" opacity=".2"/><rect x="50" y="15" width="11" height="11" rx="2" stroke="currentColor"/>{[[10,8],[10,32],[103,8],[103,32]].map(([x,y])=><circle key={`${x}-${y}`} cx={x} cy={y} r="3" fill="currentColor"/>)}</>}</svg>}
export {ZoomIn,ZoomOut};
