export interface CaseDefinition { id:string; name:string; domain:string; tagline:string; duration:string; brief:string[]; requirements:string[]; change:string; reference:Record<string,string[]>; questions:{question:string;answer:string}[]; risks:string[]; tasks:{id:string;title:string;effort:number;depends:string[];essential:boolean;acceptance:string}[] }
export const cases:CaseDefinition[]=[
{id:'webshop',name:'Fjord & Field',domain:'Retail · worked case',tagline:'From a shop-floor problem to a dependable online order.',duration:'60–90 min',brief:[
'Fjord & Field is a small Danish outdoor retailer with a physical shop. Customers currently call or email to ask about products and place orders. Employees copy details into a spreadsheet, reply with payment instructions and arrange collection or delivery. The owner wants a webshop so customers can order outside opening hours and staff spend less time repeating the same administration.',
'The owner imagines a product catalogue with categories, search, product information and a basket. Customers should be able to place an order and understand what happens next. Employees need to find orders and process fulfilment. The owner also wants to update products and prices without asking a developer. The shop already uses an external payment provider, but nobody in this meeting knows the details of its integration.',
'Stock is tracked in a spreadsheet updated by several employees. Products are also sold in the physical shop. Staff worry about promising items they cannot supply, receiving the same order twice and losing track of payments that do not finish normally. Product prices change over time; an old order must continue to show the price the customer agreed to.',
'A seasonal campaign begins in six weeks. The owner has also mentioned recommendations, discounts, loyalty points and detailed sales reports, but has not agreed which are essential for the first release. Customers often use phones; employees mainly use a shared desktop at the shop.',
'You are the consultant. Lead a conversation to understand the important needs, propose a coherent first release and explain how the screens, data, system and delivery fit together. Make assumptions visible, discuss alternatives and identify what needs investigation before the team can commit.'
],requirements:['Customers can place an order and see its current status.','Staff can find orders and process fulfilment.','Historical orders retain their agreed unit prices.','The first release must avoid overselling its allocated online stock.','A repeat request must not create a second order for the same intent.'],change:'The owner now requires the webshop and physical shop to sell from the same stock pool. The spreadsheet cannot reserve items atomically. Revisit your availability promise and integration strategy.',
questions:[{question:'Which outcome matters most for the first release?',answer:'Customers can order and staff can fulfil those orders. Recommendations and loyalty points may wait.'},{question:'Can we allocate a separate stock quantity to online sales initially?',answer:'For this worked baseline, yes. Staff will adjust a designated online allocation; do not promise real-time shared stock.'},{question:'Must customers create an account?',answer:'For the baseline, registered customer ordering is sufficient. Guest checkout is an explicit later design variation.'},{question:'What do we know about the payment provider?',answer:'An API is available, but authentication, operation identity, webhook verification and reconciliation need an early technical investigation.'}],risks:['Inventory freshness and shared physical stock','Payment uncertainty and provider capabilities','Staff ownership of pending orders'],reference:{
Goal:['Reduce manual order administration and allow ordering outside opening hours. Agree how staff time and unsuccessful orders will be observed; no unverified metric is assumed.','First release: catalogue, basket, order placement, payment-status handling and staff fulfilment. Evaluate an existing commerce platform before committing to custom development.'],
Users:['Customer: browse, place order, inspect own order. Staff: find and fulfil orders. Catalogue manager: maintain products and prices. Payment provider: supporting external actor. The database is inside the application boundary.'],
Flow:['Customer reviews basket → submits → server validates identity, quantity and price → atomically reserves online allocation and records pending order → calls provider with stable operation identity → shows known or pending outcome.','Insufficient stock preserves the basket. A timeout means unknown until reconciliation. Staff can identify unresolved operations.'],
Screens:['Customer: catalogue with category/search, product detail, basket/checkout, order status/history. Staff: filterable orders table and order detail with allowed fulfilment actions.','Checkout shows quantity, agreed price, currency, total, contact details and a clear submit action. Include loading, out-of-stock recovery and pending-payment states.'],
Data:['Customer 1 ← 0..* Order; each registered-customer baseline order has one customer. Order 1 ↔ 1..* OrderLine for submitted orders. Each line references one Product; Product may appear in 0..* lines.','OrderLine holds quantity and agreed unitPriceMinor; Order holds currency. Product holds currentPriceMinor and active. ProductCategory resolves many-to-many membership. Order has 0..* PaymentAttempts with distinct operation identities and explicit status.','NOT NULL OrderLine.order_id does not force every order to have a line. Submission logic enforces that. Do not add UNIQUE to order_id if multiple lines are allowed.'],
System:['A React frontend, modular Spring Boot backend and relational database are a plausible custom design given the stated experience. Controllers handle HTTP, services coordinate rules, repositories persist data, and an adapter isolates payment details.','Commit reservation and pending operation locally before the external payment call. Record known outcomes in another transaction. Reconcile pending operations after crashes; local rollback does not undo external payment. Keep provider secrets on the server.'],
API:['GET /api/products?category=camping&page=1; POST /api/orders with an operation key; GET /api/orders/{id} with object-level access checks. Staff price changes use a separate authorised operation.','Return validated server prices. Repeat identical intent returns the recorded result. Conflicting reuse of a key is rejected in this lab’s contract. Verify and deduplicate provider events.'],
Tests:['Given two units bought at DKK 500, when the catalogue price becomes DKK 600, then the old order still shows unit DKK 500 and total DKK 1,000.','Two competing reservations of the last item produce at most one successful reservation. A repeated order key creates no duplicate. Another customer cannot view the order. Duplicate webhook processing changes state once.'],
Delivery:['Investigate provider and stock integration early. Deliver catalogue and one complete order path, demonstrate it, then staff fulfilment and recovery. Preserve core tests and access checks when scope changes.','Rehearse data import, obtain acceptance, train staff and assign support ownership. Monitor unresolved payments and test restoration. Recommendations and loyalty are deferred unless the customer changes priorities.'],
Tradeoffs:['A separate online allocation limits integration work but needs operational discipline and does not promise shared real-time stock. The new requirement invalidates that assumption. Options include integrating with a reservation-capable stock system, replacing the source of truth or negotiating a weaker availability promise.','An existing commerce platform may be preferable for standard retail. Custom development is a practice baseline, not the only defensible solution.']},tasks:[]},
{id:'courses',name:'Byens Aftenskole',domain:'Education · transfer case',tagline:'Capacity, prerequisites and a waiting list that moves fairly.',duration:'40–60 min',brief:[
'A community learning centre offers evening courses across three venues. Each course can have several scheduled sessions, each with its own dates, instructor, room and capacity. Staff currently manage bookings through email and spreadsheets. Learners cannot tell which sessions have places, and staff repeatedly contact people when a place becomes free.',
'The centre wants a service where learners find a suitable session, register and understand whether their booking is confirmed or waitlisted. Some advanced sessions require completion of an earlier course. Instructors need attendance lists but should not see unrelated personal information. Administrators schedule sessions and resolve booking problems.',
'The centre wants to open registrations in six weeks. It does not collect payment through this system. Rooms and instructors must not be double-booked. Cancellations may release a place, but the staff have not yet agreed how long a waitlisted learner should have to accept an offer. Learners use phones and staff use desktops.',
'Lead discovery, choose an explicit waiting-list policy and propose the screens, data, APIs, quality checks and delivery needed for a useful first release. Identify which rules require a customer decision.'
],requirements:['A learner can register for a specific course session.','Confirmed bookings cannot exceed session capacity.','Only eligible learners can register for advanced sessions.','A released place follows an agreed waiting-list policy.','Rooms and instructors cannot have overlapping sessions.'],change:'Waitlisted learners now need 24 hours to accept an offered place. An offer reserves capacity until accepted or expired; the next person must then be offered the place.',questions:[{question:'Is a course the same as a scheduled session?',answer:'No. A course describes content; a session is one scheduled offering with capacity, dates, instructor and room.'},{question:'What happens when a session is full?',answer:'Baseline: learners can join a FIFO waiting list and staff promote the next eligible person when a place opens.'},{question:'Who decides eligibility?',answer:'Completed prerequisite records determine eligibility; staff may record an explicitly justified override.'},{question:'Do we need payment?',answer:'No payment workflow belongs in this case.'}],risks:['Concurrent capacity allocation','Waiting-list fairness and expiry policy','Room and instructor schedule conflicts'],reference:{
Goal:['Reduce manual registration and make capacity and waiting-list outcomes clear. Agree the first-release waiting-list policy rather than importing webshop payment behaviour.'],Users:['Learner, instructor and administrator are distinct actors. Instructors see only their session lists; administrators manage scheduling and exceptions.'],Flow:['Choose session → check prerequisite eligibility → reserve capacity atomically if available → confirm booking, otherwise offer waiting-list registration. Cancellation releases capacity and triggers the agreed promotion process.'],Screens:['Session search with dates and remaining availability; session detail with prerequisite explanation; booking/wait-list status; staff scheduling and promotion queue. Explain why registration is unavailable without exposing others’ information.'],Data:['Course describes a subject; Session is a scheduled occurrence. Booking connects Learner to Session with a unique active-membership policy. Completion supports prerequisite evidence; CoursePrerequisite is a self-referencing association.','WaitingListEntry records joinedAt and state. Room and Instructor allocations include time intervals. The changed policy adds Offer with expiresAt and an explicit held-capacity rule.'],System:['A modular application and relational database can coordinate capacity and booking atomically. A scheduled process expires offers; a notification adapter sends messages. Durable status is authoritative even if email delivery fails.'],API:['GET /sessions with date and subject filters; POST /sessions/{id}/bookings derives learner from identity; DELETE /bookings/{id} checks ownership. Staff overrides require a distinct permission and audit explanation.'],Tests:['Two eligible learners compete for one place: one confirmed booking maximum. Ineligible learner cannot self-approve. Cancellation promotes according to policy. An expired offer cannot be accepted. Adjacent non-overlapping room intervals are allowed under the declared end-exclusive rule.'],Delivery:['Clarify waiting-list and eligibility rules, then deliver one session listing and booking path. Add cancellation/promotion, staff schedule checks and notifications. Rehearse import of completion records and train staff.'],Tradeoffs:['A booking is not an order line. Time, eligibility and waiting-list state drive this model. Under the new policy, an offer is a temporary reservation, not an immediate confirmed booking.','Checking interval conflicts needs concurrency-safe enforcement, not just a UI calendar. A simple staff review can be an explicit temporary constraint if the customer accepts it.']},tasks:[]},
{id:'rental',name:'Grejbanken',domain:'Equipment · transfer case',tagline:'Reserve an actual item, return it, and handle what changes.',duration:'40–60 min',brief:[
'A municipal equipment library lends tools and outdoor equipment to registered members. A catalogue lists equipment types, but staff need to track individual physical items because identical drills may have different maintenance histories. Reservations cover a date range, and members collect and return items at a staffed desk.',
'Today staff use a shared calendar and paper condition notes. They sometimes promise an item that has not yet returned, and damaged equipment can accidentally be loaned again. The library wants members to browse availability and reserve equipment, while staff record collection, return and condition.',
'The first release is needed for a seasonal opening in six weeks. There is no online payment requirement. Staff must be able to mark an item unavailable for maintenance. The rules for late returns, substitution and how far ahead a specific asset is assigned are not yet agreed. The library values a clear explanation when a reservation cannot be honoured.',
'Act as the consultant: clarify the time and allocation rules, design a coherent reservation and handover flow, and propose a realistic delivery plan. Show how a late return or damaged item affects the solution.'
],requirements:['Members can request equipment for an explicit time interval.','An asset cannot be allocated to overlapping reservations.','Staff record collection and return separately.','Items under maintenance are unavailable for new allocation.','A late or damaged return creates a visible exception for affected bookings.'],change:'An item is returned damaged on the morning of its next reservation. Staff want to substitute an equivalent asset while preserving the original reservation and an audit of the change.',questions:[{question:'What is an equipment type versus an asset?',answer:'“18V drill” is a type. Asset D-17 is one physical drill with its own condition and maintenance record.'},{question:'When do we allocate a specific item?',answer:'Baseline: allocate a specific asset at reservation confirmation. Other allocation strategies are possible but must be explained.'},{question:'How are time boundaries read?',answer:'Use end-exclusive intervals: a reservation ending at 12:00 does not overlap one starting at 12:00. A preparation buffer is a separate policy.'},{question:'Can members collect without staff?',answer:'No. Staff record collection, condition and return in the baseline.'}],risks:['Overlapping allocations under concurrency','Late returns affecting later promises','Maintenance and substitution history'],reference:{
Goal:['Make reliable reservations and keep item condition visible. Clarify interval boundaries and operational response to late returns.'],Users:['Member reserves and checks status; staff confirm handover and return; maintenance staff change service availability.'],Flow:['Choose equipment type and interval → allocate a suitable available asset → confirm reservation → staff record collection → staff record return and condition. Late or damaged returns create an exception workflow.'],Screens:['Availability search with dates; reservation review; member reservation status; staff handover/return form with condition notes; maintenance and affected-reservation queue.'],Data:['EquipmentType has many Assets. Reservation has an interval and member. Allocation connects a reservation to an asset; Handover/Return records actual times and condition. Maintenance blocks allocation.','Use end-exclusive overlap: startA < endB AND startB < endA. A current Boolean available flag cannot express future availability. Changed requirements can add allocation history with replacement reason rather than overwriting the original assignment.'],System:['A relational application owns allocation. Protect overlap checks and insertion against concurrent reservations using a deliberate locking or constraint strategy. Notifications are separate from the durable reservation state.'],API:['GET /availability?type=drill&from=…&to=…; POST /reservations; staff-only POST /reservations/{id}/collection and /return. Validate time range and object access.'],Tests:['Overlapping reservations cannot share an asset. Adjacent intervals are allowed under the declared rule. Maintenance excludes an asset. A late return raises an affected-booking exception. A substitution preserves reservation identity and records the asset change.'],Delivery:['Clarify allocation and interval policy, then build search → reserve → staff handover for one equipment type. Add return/maintenance handling, conflict tests, import asset inventory and train staff.'],Tradeoffs:['Assigning assets early gives a concrete promise but reduces flexibility. Late assignment may improve utilisation but needs capacity-by-type reasoning. Both need clear exception handling.','This is a time-allocation problem: replacing price and stock fields from a webshop is not enough. A reservation is not proof that the asset was actually returned.']},tasks:[]}
];
for(const c of cases)c.tasks=[
{id:'discovery',title:'Agree critical flow & rules',effort:2,depends:[],essential:true,acceptance:'Customer confirms actors, scope and outstanding questions.'},
{id:'risk',title:c.id==='webshop'?'Prove payment & stock integration':c.id==='courses'?'Prove capacity & eligibility rules':'Prove interval allocation',effort:3,depends:['discovery'],essential:true,acceptance:'Demonstrate the riskiest integration or concurrency rule with a focused fixture.'},
{id:'slice',title:c.id==='webshop'?'One complete customer order':c.id==='courses'?'One complete session booking':'One complete reservation',effort:6,depends:['discovery','risk'],essential:true,acceptance:'One user can complete the critical flow with durable state and access checks.'},
{id:'staff',title:'Staff workflow & recovery',effort:4,depends:['slice'],essential:true,acceptance:'Staff can process the result and resolve a failure without losing history.'},
{id:'extras',title:c.id==='webshop'?'Recommendations & loyalty':'Advanced reporting',effort:7,depends:['slice'],essential:false,acceptance:'Customer confirms the additional feature actually helps the intended task.'},
{id:'acceptance',title:'Acceptance, migration & training',effort:3,depends:['staff'],essential:true,acceptance:'Rehearsal passes, customer accepts and staff can operate the service.'},
{id:'launch',title:'Launch & support handover',effort:2,depends:['acceptance'],essential:true,acceptance:'Monitoring, tested recovery and named support ownership are in place.'}];
export interface Beat { title:string;role:'Customer'|'Technical colleague';prompt:string;choices:{text:string;reply:string;helpful:boolean}[];criteria:string[] }
export function dialogue(caseId:string):Beat[]{ const c=cases.find(x=>x.id===caseId)!; const core=caseId==='webshop'?'placing and fulfilling an order':caseId==='courses'?'booking an eligible learner into a session':'reserving and handing over an available asset';return [
{title:'Open the conversation',role:'Customer',prompt:`You have read our brief. Where would you like to start?`,choices:[{text:'Restate the goal and ask what matters most',reply:`Yes. We need ${core} to work reliably. Let’s start there.`,helpful:true},{text:'Start listing frameworks',reply:'Before technology, can you explain what problem you think we need to solve?',helpful:false},{text:'Ask about the logo',reply:'We can discuss branding later. The manual work and mistakes are more urgent.',helpful:false}],criteria:['Restate the outcome','Invite correction']},
{title:'Clarify a decision',role:'Customer',prompt:c.questions[0].question+' What would you ask or clarify?',choices:[{text:'Clarify the domain distinction and its consequences',reply:c.questions[0].answer,helpful:true},{text:'Assume the simplest rule without checking',reply:'That assumption may be wrong. Please make it explicit and check with me.',helpful:false}],criteria:['Name an uncertainty','Connect it to a design decision']},
{title:'Draw the first flow',role:'Customer',prompt:`Talk me through ${core} from beginning to end.`,choices:[{text:'Follow the user through success and one failure',reply:'That makes sense. What does the user see if the operation cannot finish?',helpful:true},{text:'Only list database tables',reply:'I cannot yet see how a person completes the task. Can you walk through it?',helpful:false}],criteria:['Identify actor and start','Describe success','Include recovery']},
{title:'Agree a first release',role:'Customer',prompt:'We would like all the extras too. Can everything be in the first release?',choices:[{text:'Ask which complete outcome must come first',reply:'The core flow and staff handling matter most. Extras can follow if we agree the impact.',helpful:true},{text:'Commit to everything immediately',reply:'How will you leave room to investigate the risky part and test it?',helpful:false},{text:'Reject the request without discussing options',reply:'Then what useful smaller solution can you offer?',helpful:false}],criteria:['Give a scope option','Explain the consequence','Ask for agreement']},
{title:'Explain the screen',role:'Customer',prompt:'Show me the most important screen and why you arranged it that way.',choices:[{text:'Connect information and actions to the user’s goal',reply:'I can follow that. Please include what happens when something goes wrong.',helpful:true},{text:'Just say it looks modern',reply:'How does that help someone complete this particular task?',helpful:false}],criteria:['Use your wireframe','Explain hierarchy','Include an error state']},
{title:'Defend the data model',role:'Technical colleague',prompt:caseId==='webshop'?'Why do you need OrderLine, and where does the agreed price belong?':caseId==='courses'?'Why separate Course from Session, and how does waiting-list state fit?':'Why separate EquipmentType, Asset and Reservation?',choices:[{text:'Use a concrete example and read both relationship directions',reply:'Good. Now distinguish the database constraints from the workflow rules.',helpful:true},{text:'Say the ORM will decide the relationships',reply:'The ORM maps a decision; it does not decide the business meaning for us.',helpful:false}],criteria:['Explain each entity’s responsibility','Read both multiplicities','State an integrity rule']},
{title:'Trace a request',role:'Technical colleague',prompt:'Where do validation, authorisation and durable changes occur?',choices:[{text:'Trace browser → trusted service → local transaction → external boundary',reply:'Now explain which changes are atomic and which are outside that transaction.',helpful:true},{text:'Rely on frontend checks',reply:'What prevents a caller from bypassing the browser?',helpful:false}],criteria:['Server checks','Object-level permission','Explicit transaction boundary']},
{title:'Reason about uncertainty',role:'Technical colleague',prompt:caseId==='webshop'?'The provider times out after payment may have succeeded. What now?':caseId==='courses'?'Two learners compete for the final place. What protects capacity?':'Two members request overlapping dates for the same asset. What protects the promise?',choices:[{text:'Name the invariant and use a mechanism that protects it',reply:caseId==='webshop'?'Keep the outcome pending, use the same operation identity and reconcile. Do not assume failure.':'The check and mutation must be protected together. Show how a conflict is handled for the user.',helpful:true},{text:'Assume it never happens in a small system',reply:'Even two users are enough. Please revise the failure path.',helpful:false}],criteria:['Name the invariant or uncertainty','Show a safe mechanism','Explain user outcome']},
{title:'A new requirement',role:'Customer',prompt:c.change,choices:[{text:'Acknowledge the change and review linked artefacts',reply:'Please explain what changes in scope, data, screens and tests, and what you need me to decide.',helpful:true},{text:'Defend the original design without revisiting it',reply:'The original assumption no longer holds. Can you propose alternatives?',helpful:false}],criteria:['Name the invalidated assumption','Revise connected artefacts','Offer options']},
{title:'Make it simpler',role:'Customer',prompt:'Could you explain that without technical terminology?',choices:[{text:'Use the customer’s task and a concrete example',reply:'That helps. I understand the consequence now.',helpful:true},{text:'Repeat the same technical terms more slowly',reply:'I still need to know what this means for our users and staff.',helpful:false}],criteria:['Avoid unexplained jargon','Preserve the important meaning']},
{title:'The deadline moves',role:'Customer',prompt:'We need to launch in four weeks instead of six. What would you change?',choices:[{text:'Negotiate a coherent scope and retain essential quality',reply:'Show me what is deferred and what we can still complete from start to finish.',helpful:true},{text:'Remove security and recovery tests',reply:'That leaves us exposed to the failures we just discussed. Find a scope tradeoff.',helpful:false}],criteria:['Reorder delivery','Name deferral','Protect essential quality']},
{title:'Close with a decision',role:'Customer',prompt:'Summarise your proposal, the main tradeoff and what happens next.',choices:[{text:'Summarise outcomes, decisions, risks and next actions',reply:'Thank you. That gives us a clear basis for the next conversation.',helpful:true},{text:'End with only a technology list',reply:'I also need to know what we are getting, what remains uncertain and who does what next.',helpful:false}],criteria:['User outcome','Coherent solution','Tradeoff and risk','Next action and invitation to correct']}
];}
