import type { Exercise, GradeKind, ItemType } from '../domain/types';
type O = [string,string,boolean?];
const q=(id:string,title:string,prompt:string,options:O[],explanation:string,hint:string,type:ItemType='choice',grade:GradeKind='objective',assumptions?:string):Exercise=>({id,module:id[0],title,prompt,type,grade,assumptions,options:options.map(([text,feedback],i)=>({id:String(i),text,feedback})),answer:options.flatMap((o,i)=>o[2]?[String(i)]:[]),hints:[hint,'Test your choice against a concrete example in the prompt.'],explanation});
const open=(id:string,title:string,prompt:string,criteria:string[],explanation:string,speak=false):Exercise=>({id,module:id[0],title,prompt,type:speak?'speak':'explain',grade:'rubric',options:[],answer:[],criteria,hints:['Name the actor, the decision and the consequence.','Use one concrete example and make your assumptions explicit.'],explanation});
const order=(id:string,title:string,prompt:string,steps:string[],explanation:string):Exercise=>({id,module:id[0],title,prompt,type:'order',grade:'scenario',options:steps.map((text,i)=>({id:String(i),text,feedback:`Position ${i+1}: ${text}`})),answer:steps.map((_,i)=>String(i)),hints:['Look for a dependency: what must be true before the next action?','Distinguish a prerequisite from something that could happen in parallel.'],explanation});
const match=(id:string,title:string,prompt:string,pairs:[string,string][],explanation:string):Exercise=>({id,module:id[0],title,prompt,type:'match',grade:'objective',options:pairs.map(([text,feedback],i)=>({id:String(i),text,feedback})),pairs:pairs.map(p=>p[1]),answer:pairs.map((_,i)=>String(i)),hints:['Match by meaning rather than familiar vocabulary.','Check each pair with an example of your own.'],explanation});
export const exercises:Exercise[]=[
q('A1','The first useful question','The customer asks for an app to reduce order-handling effort. Which question best opens discovery?',[
['Which CSS framework do you prefer?','Premature: it does not yet explain the business problem.'],['Where does order handling take the most time today?','This exposes the current problem and the highest-value flow.',true],['Can we use microservices?','A technology proposal comes before understanding the need.']], 'Begin with the current pain, actor and desired outcome. Technology can follow.','Ask what answer would change the first-release scope.'),
q('A2','Separate evidence from belief','A colleague says “I assume the spreadsheet is always up to date.” How should you record this?',[
['Confirmed fact','No one has confirmed its reliability.'],['Assumption to validate','Keep the belief visible and assign a way to check it.',true],['Acceptance criterion','It does not describe an observable result of the new system.']], 'Assumptions can support provisional design, but must not silently become facts.','Notice the source and certainty of the statement.'),
q('A3','High-value discovery','Before promising online stock availability, which questions could materially change the solution?',[
['Is stock shared with the physical shop?','This changes concurrency and source-of-truth requirements.',true],['Who updates the inventory and how often?','This reveals freshness and ownership.',true],['Should the logo be round?','Branding can wait; it does not establish availability.'],['Can stock be reserved in the existing system?','This determines whether reliable reservation is possible.',true]], 'Ask about ownership, freshness and reservation before promising real-time availability.','Think about other actors changing the same stock.','multi','scenario','The first release must avoid promising items it cannot fulfil.'),
q('A4','A measurable quality requirement','Which statement is most useful to negotiate as a nonfunctional requirement?',[
['The system should be good','It is too vague to verify.'],['Customers can cancel an order','This is functional behaviour.'],['Agree a response-time target for product search at the expected load','This turns performance into an observable quality target.',true]], 'The actual target must come from context; do not invent a performance promise.','Separate behaviour from the quality of that behaviour.'),
q('A5','Enough clarification to draw','You know the main actor, goal and critical flow, but discount rules are unresolved. What next?',[
['Wait until every question is settled','This delays feedback on useful provisional work.'],['Draw a provisional flow and label the discount question','Progress while keeping uncertainty visible.',true],['Assume all discounts stack','An unconfirmed commercial rule is risky.']], 'Move between discovery and design. A labelled assumption invites correction.','Can you start without concealing what remains unknown?','choice','scenario'),
open('A6','Build or buy','A small retailer has standard catalogue, payment and fulfilment needs. Compare an existing commerce platform with a custom Spring/React solution.',['Identify likely standard capabilities','Consider integration and data ownership','Consider team skills and ongoing operations','State evidence that would change your recommendation'],'A platform may reduce initial work, but unusual integrations, contractual constraints or custom workflows can change the choice. Compare total responsibility, not only licence cost.'),
q('A7','Respond to correction','Kasper says your assumption about customer accounts is wrong: guest checkout is essential. Choose the best response.',[
['Accounts are more modern, so keep them','This ignores a clarified need.'],['Thank him, update the actor/data assumptions and check order access','This connects the new fact to design consequences.',true],['Delete Customer immediately and continue silently','There may still be registered customers; explain the revised model.']], 'Course correction is a visible reasoning skill. Guest contact and secure order lookup need deliberate treatment.','Acknowledge, revise and involve the customer.','choice','scenario'),
open('A8','Close the consultation','Give a 45-second summary after choosing a first release with online ordering and staff fulfilment.',['Restate the customer outcome','Name a scope decision and its reason','Name an unresolved risk and an owner or next action','Invite confirmation'],'A useful close makes the agreed direction and the remaining uncertainty easy to correct.',true),
q('B1','Who is an actor?','The webshop includes its own database. Which are external actors?',[
['Customer','A role interacting with the system.',true],['Internal orders database','This is an internal implementation component.'],['External payment provider','An external system can be a supporting actor.',true],['Fulfilment employee','This role interacts with the staff interface.',true]], 'Draw the system boundary first; externality depends on that boundary.','Ask what sits outside the named system.','multi'),
q('B2','Goal or click?','Which is the best use-case name?',[
['Click the blue button','This describes an interface action.'],['Place an order','This expresses an actor goal.',true],['Run SELECT','This describes an implementation operation.']], 'A use case follows an actor to a meaningful outcome, potentially across several screens.','What does the person want to accomplish?'),
match('B3','Parts of a use case','Match the use-case term to its meaning.',[['Precondition','Must already hold before the flow starts'],['Postcondition','Guaranteed state after the flow'],['Alternative flow','A different path such as unavailable stock'],['Main flow','The usual successful interaction']], 'Preconditions are not simply the first action. Alternatives deserve explicit outcomes.'),
q('B4','Acceptance that can be checked','Which criterion can be observed clearly?',[
['Checkout is intuitive','Useful aspiration, but insufficient as a test criterion.'],['Given unavailable stock, submitting preserves the basket and identifies the affected line','A concrete setup, action and result.',true],['The developer finishes checkout','This measures work completion rather than behaviour.']], 'Use concrete examples, including failures, to agree what the feature must do.','Look for context, action and result.'),
order('B5','An order use case','Order this simplified successful flow. The customer has already selected products.',['Review basket and fulfilment details','Submit the order request','Validate and reserve available stock','Show the recorded order and current payment status'],'This fixture puts reservation before the resulting confirmation. Unknown payment status must remain visible; a recorded order is not necessarily paid.'),
open('B6','Tell the alternative story','Write the main and alternative flow for joining a course that might be full.',['Identify learner and course session','State capacity check','Describe confirmed booking outcome','Describe waiting-list or rejection alternative under an explicit rule'],'A course session is a scheduled offering. A full session can lead to a waiting list if the customer wants one; do not silently invent that policy.'),
q('C1','The useful empty state','A staff member opens the first-ever order list. Which empty state helps most?',[
['An empty grid with no text','The employee cannot tell whether this is a failure.'],['No orders yet. New orders will appear here; clear filters to check all orders.','Explains the situation and a relevant action.',true],['Error: no data','No orders is not necessarily an error.']], 'Distinguish a valid empty result from a failed request.','What uncertainty does the user have now?'),
q('C2','Preserve the user’s work','An address validation error occurs. Which behaviours help?',[
['Keep previously entered values','Avoids unnecessary re-entry.',true],['Label the invalid field and explain how to correct it','Makes recovery actionable.',true],['Reset all fields for safety','Usually punishes the user without solving the problem.'],['Indicate the error with red alone','Colour alone does not communicate accessibly.']], 'Good error recovery preserves work and provides specific guidance.','Consider keyboard users and someone who cannot perceive the colour.','multi'),
q('C3','Staff and customer needs','Staff process many orders; customers place one order. Which design direction is most defensible?',[
['Use exactly the same screen for both','The tasks and information density differ.'],['Staff status table and customer step-by-step checkout','Each supports a different goal.',true],['Hide status from staff to reduce clutter','It removes information needed to fulfil orders.']], 'Choose layouts according to actor tasks, not a universal preference for cards or tables.','What information must each actor compare?','choice','scenario'),
q('C4','What can a checker know?','A wireframe checker finds a labelled email field and submit button. What can it conclude?',[
['The entire design is intuitive','Presence checks cannot establish that.'],['Those declared components are present','That is the scope of the structural check.',true],['All users can complete checkout','Task testing and further review are needed.']], 'Structural evidence and usability judgment should be reported separately.','Separate inspectable facts from an overall judgment.'),
open('C5','Repair an error state','A checkout displays only “Error 409.” Propose a better message and recovery interaction for insufficient stock.',['Name the affected item and availability','Offer a specific correction','Preserve the rest of the basket','Avoid presenting internal codes as the whole explanation'],'For example: “Only one tent remains. Change the quantity to one to continue.” Let the customer edit without restarting.'),
q('C6','Accessible interaction','Which are appropriate alternatives to dragging a wireframe component?',[
['Move up / Move down buttons with visible focus','Works with keyboard and simple pointer clicks.',true],['A keyboard-only hidden shortcut','It does not provide a discoverable pointer alternative by itself.'],['A labelled position control','Offers another way to rearrange items.',true]], 'Important drag operations need accessible alternatives, including a way to operate without dragging.','Think beyond mouse versus keyboard alone.','multi'),
open('C7','Explain your screen','Explain why your checkout puts the summary before the final action. Then identify one downside.',['Connect the choice to reviewing the agreement','Discuss a concrete information hierarchy','Recognise a tradeoff such as screen length','Explain how you would validate the design'],'The customer should see what they are agreeing to, but a long summary may need progressive disclosure on a small screen.',true),
q('D1','Read the endpoint','UML: Order “1” — “1..*” OrderLine. What does 1..* beside OrderLine mean?',[
['Each line has many orders','That would be described at the Order endpoint.'],['Each order has one or more lines','Read the number at the far entity when starting from one order.',true],['Every product has one order','Product is not part of this relationship.']], 'Read both directions: one order has one or more lines; one line belongs to exactly one order.','Start with one Order and look across to OrderLine.'),
q('D2','Why an OrderLine?','Where should the quantity of a product in a particular order live?',[
['Product.quantity','That confuses catalogue data with a particular purchase.'],['OrderLine.quantity','The value belongs to the product occurrence in this order.',true],['Customer.quantity','Quantity is not a customer property.']], 'An associative entity holds facts about the relationship, not only foreign keys.','The same product appears in different orders with different quantities.'),
q('D3','The historical price','A product changes from DKK 500 to DKK 600 after purchase. How should the old order obtain its agreed unit price?',[
['Read Product.currentPrice each time','This rewrites history.'],['Read the stored OrderLine agreed price and currency','This preserves the commercial fact.',true],['Prohibit future price changes','This unnecessarily restricts catalogue management.']], 'A price snapshot has different meaning from current catalogue price. This duplication is intentional.','Which question does each price answer?'),
q('D4','Foreign-key limits','OrderLine.order_id is a NOT NULL foreign key. Which are guaranteed by these constraints alone?',[
['Each line references an existing order','Non-null plus foreign key enforces this.',true],['Every order has at least one line','A parent can exist with no child rows.'],['No order has more than one line','That would need uniqueness on order_id.'],['A line cannot have a null order_id','NOT NULL enforces this.',true]], 'Child-side constraints do not guarantee a minimum child count for every parent.','Imagine inserting only an Order row.','multi'),
q('D5','The accidental one-to-one','A developer adds UNIQUE to OrderLine.order_id. What happens?',[
['One order can have at most one line','Repeated order_id values are rejected.',true],['Each line can have many orders','The foreign key still points to one order.'],['Orders must have a line','Uniqueness does not require child existence.']], 'Use uniqueness only when the business rule demands it.','Try inserting two lines with the same order ID.'),
q('D6','Guest checkout','Guest checkout is allowed. What is a plausible relationship to a registered Customer?',[
['Order requires exactly one registered Customer','That contradicts the declared guest flow.'],['Order references zero or one registered Customer, with required contact handled separately','Optional account linkage and contact obligations are different.',true],['Order needs no contact information ever','Guest does not imply unreachable.']], 'This is one valid model under explicit assumptions; an alternative guest identity model could also work.','Separate an account from fulfilment contact.','choice','scenario'),
q('D7','Multiple categories','A product can belong to several categories; each category has many products. What relational structure fits?',[
['A comma-separated category list in Product','Hard to constrain and query as relationships.'],['ProductCategory with foreign keys to both tables','Represents the many-to-many association.',true],['One mandatory product_id in Category','Limits a category to one product.']], 'Add a uniqueness constraint on the pair if duplicate memberships are forbidden.','Where can you represent each membership as a row?'),
q('D8','Retire a referenced product','Historical order lines refer to a discontinued product. Which policy best preserves the stated history requirement?',[
['Cascade delete every historical order line','Destroys agreed historical facts.'],['Deactivate the product for new sales and retain required history','Preserves references while changing sale availability.',true],['Change all old lines to a replacement product','Misrepresents what was bought.']], 'Retention and anonymisation rules still need clarification. Deactivation is a modelling option, not permission to retain all data forever.','Separate availability for new use from historical existence.','choice','scenario'),
open('D9','Draft or submitted?','Two diagrams disagree: an order has 0..* versus 1..* lines. Explain how both can be reasonable.',['State which lifecycle each diagram models','Explain empty drafts','Require at least one line at submission','Identify how the rule is enforced'],'If drafts are included, zero lines can be valid before submission. A submitted-only conceptual model can require one or more. The workflow must preserve the intended rule.'),
match('D10','Keys and constraints','Match the mechanism to its main meaning.',[['Primary key','Uniquely identifies a row and is not null'],['Foreign key','References a permitted key in another or the same table'],['Unique constraint','Prevents duplicate constrained values under the database’s null semantics'],['NOT NULL','Requires a value in that column']], 'These mechanisms complement business rules; no single one establishes all relationship semantics.'),
q('E1','Trusted validation','The browser validates quantity. Where must the business rule also be enforced?',[
['Only the browser; users cannot change it','Requests can bypass the interface.'],['The backend at the trusted boundary','The server must protect its data regardless of caller.',true],['Only in user documentation','Documentation cannot enforce integrity.']], 'UI validation helps usability; backend validation protects the service.','Imagine a caller sending HTTP directly.'),
match('E2','Responsibility boundaries','Match a common application responsibility.',[['Controller','Translate HTTP input and output'],['Service','Coordinate a business use case'],['Repository','Read or write through persistence abstractions'],['External adapter','Encapsulate a provider-specific contract']], 'These are useful responsibilities, not a requirement for identical class structures in every application.'),
q('E3','Proportionate architecture','A small team has six weeks and no independent scaling need. Which starting point is best justified?',[
['Seven microservices because it is modern','Adds operational complexity without a stated benefit.'],['A modular monolith with clear boundaries','Matches the stated constraints while preserving structure.',true],['No backend validation to save time','Sacrifices a trust boundary.']], 'Revisit the decision if team, deployment or scaling requirements change.','Account for who will operate the system.','choice','scenario'),
q('E4','Asynchronous consequences','Which obligations can follow from processing payment notifications asynchronously?',[
['Expose pending status','Users need an honest account of progress.',true],['Handle duplicate and delayed messages','Delivery timing is not fully controlled.',true],['Assume failure cannot happen','Moving work does not remove failure.'],['Monitor stuck operations','Someone must notice and recover them.',true]], 'Asynchrony can decouple timing while increasing state and operational responsibilities.','What happens between request acceptance and final completion?','multi'),
q('E5','Where secrets belong','Where should the payment provider secret be configured?',[
['In a frontend environment variable bundled into JavaScript','Browser bundles are visible to users.'],['In protected server-side configuration','Only the trusted server should receive it.',true],['In a public repository comment','This exposes credentials.']], 'Environment-variable syntax does not make a value secret if it is shipped to the browser.','Who can download the compiled frontend?'),
open('E6','Backups are not recovery','The proposal says “nightly backups” and nothing more. Add a useful recovery plan.',['Identify an owner','Set recovery expectations with the customer','Test restoration and data consistency','Consider failure detection and access to backups'],'A backup is useful only when it can be restored in time, with acceptable loss and verified data.'),
open('E7','Explain the architecture','Explain a React / Spring Boot / relational database design to a nontechnical retailer.',['Connect the browser to customer tasks','Explain business-rule enforcement simply','Explain durable order records','State one reason this fits and one uncertainty'],'“The website is the counter, the application checks and coordinates orders, and the database preserves the agreed details.” Follow the analogy with a concrete user action.',true),
q('F1','Read or create?','Which request most naturally retrieves one existing order?',[
['GET /api/orders/o-1','Retrieves a representation of the identified resource.',true],['POST /api/getOrderNowAndDelete','Mixes unclear operations and unsafe naming.'],['DELETE /api/orders/o-1','Requests removal, not retrieval.']], 'Method semantics and the documented resource contract guide the choice.','What operation is being requested?'),
match('F2','Common HTTP outcomes','Match each status to its usual meaning.',[['201','Resource created'],['401','Authentication is missing or invalid'],['403','The action is forbidden'],['409','Conflict with current resource state']], 'These are common semantics. Design a consistent contract, including whether object existence is concealed with 404.'),
q('F3','An object-level flaw','GET /orders/{id} checks only that the caller is logged in. What important check is missing?',[
['Whether the caller owns this order or has a permitted staff role','Authorisation must concern the requested object.',true],['Whether the ID is long enough','Hard-to-guess IDs are not permission checks.'],['Whether the button is hidden','A caller can bypass the interface.']], 'Test with two distinct customers, not only anonymous and authenticated users.','Authentication answers who, not which objects.'),
q('F4','Path or query?','Which URL uses a query parameter to filter a collection?',[
['/api/products?category=camping','Category filters the products collection.',true],['/api/products/p-1','The path identifies one product.'],['/api/products#camping','The URL fragment is not sent as an HTTP query.']], 'Pagination and filtering should have explicit contracts and limits.','Look after the question mark.'),
q('F5','The price you cannot trust','A browser posts unitPriceMinor: 1 for a tent. What should the server do?',[
['Trust it because the UI normally fills it','Clients can modify requests.'],['Resolve and validate the agreed price using trusted rules','The server owns the commercial validation.',true],['Accept any positive integer','Type validation alone does not validate meaning.']], 'Validate both input shape and the business rule; preserve the resulting agreed price in the order.','Who controls the request body?'),
q('F6','Same key, different intent','A client reuses an order idempotency key with a different quantity. Under this lab’s contract, what occurs?',[
['Create another order silently','That defeats operation identity.'],['409 conflict','A key cannot represent two different intents.',true],['Overwrite the original purchase','This alters a recorded operation unexpectedly.']], 'Provider contracts differ; this lab explicitly binds a key to the original request fingerprint.','Compare identity and parameters.','choice','scenario'),
q('F7','A webhook arrives twice','Which controls belong in a production webhook design?',[
['Verify the provider signature or equivalent authenticity mechanism','Do not trust arbitrary callers.',true],['Deduplicate event IDs and process state changes safely','Repeated delivery should not repeat the side effect.',true],['Assume the IP address alone proves all content','This is not a complete authenticity strategy.'],['Monitor failed processing and arrange retries','Verified delivery can still fail during processing.',true]], 'The playground uses a declared fixture header for authenticity. Real providers require their documented verification algorithm.','Consider both who sent it and whether it was already handled.','multi'),
open('F8','Design the collection endpoint','Describe a staff order-list endpoint for a large history.',['Filter by relevant state','Use bounded pagination with an explicit contract','Apply staff authorisation','Return only needed fields','Consider stable ordering'],'An example is GET /api/orders?status=pending&limit=25&cursor=… with a defined ordering and next cursor. Offset pagination may also be adequate depending on scale and consistency needs.'),
q('G1','The last item race','Two requests read stock=1 and both later write stock=0. What is the problem?',[
['Both may confirm a sale of the same last item','The check and mutation are not protected together.',true],['A database can never accept this','Without suitable concurrency control it can.'],['The second user must have been unauthenticated','Authentication does not solve the race.']], 'Protect the invariant with a correct transaction/query strategy, such as an atomic conditional decrement.','Reading a value does not reserve it.'),
q('G2','A transaction’s boundary','A payment succeeds externally, then the local transaction rolls back. What is true?',[
['The payment automatically rolls back too','The provider is outside the local transaction.'],['The external payment may still be successful','Recovery needs reconciliation or a new compensating action.',true],['The database can delete the provider’s record','It has no such authority.']], 'A refund is a separate external operation, not a local rollback.','Which system controls the payment ledger?'),
q('G3','Timeout knowledge','The payment request times out. What can the application conclude?',[
['Payment definitely failed','The response may have been lost after success.'],['The outcome is unknown until reconciled','Represent uncertainty explicitly.',true],['Payment definitely succeeded','It may not have reached the provider.']], 'The same observed timeout can correspond to different remote outcomes.','Distinguish the event from what your system knows.'),
order('G4','A safe fixture sequence','Order the lab’s reference checkout sequence.',['Validate identity and request','Reserve stock and record pending order in a local transaction','Call provider with stable operation identity after commit','Record known outcome in another transaction or reconcile uncertainty'],'This is one authored design. Production recovery also needs to handle a crash after local commit but before the provider call.'),
q('G5','Prevent duplicate intent','Which controls help avoid duplicate operations?',[
['Stable operation identity enforced by the server','Repeated intent can resolve to the same result.',true],['Disable the button only','This helps the interface but does not protect the service alone.'],['Store the processed event identity with the state update','Atomic deduplication protects against duplicate delivery.',true]], 'A control must protect the boundary where repeats can actually occur.','What if the first response was lost?','multi'),
q('G6','Conditional stock update','An atomic UPDATE … WHERE available >= 1 affects zero rows. What should the service infer?',[
['The reservation did not succeed','The condition did not find reservable stock for this operation.',true],['The customer owns the item','No successful reservation was recorded.'],['Retry forever until it works','Unbounded retry can overload the service and conceal unavailability.']], 'Check mutation outcomes and communicate availability honestly.','Which evidence would prove reservation succeeded?'),
open('G7','Late payment notification','An order’s payment is confirmed succeeded. A delayed event reports an earlier pending state. What should your design consider?',['Do not blindly downgrade confirmed state','Use provider event/object identity and documented ordering rules','Reconcile when events conflict','Make repeated processing safe'],'Maintain a deliberate state machine and use the provider’s authoritative state where appropriate. Receipt order alone may not equal event order.'),
open('G8','Recover a stuck reservation','The application crashes after reserving stock but before calling the provider. Propose a recovery policy.',['Find pending operations durably','Check whether payment occurred before release or retry','Use stable operation identity','Define timeout, owner and user communication'],'A recovery worker can inspect pending operations and reconcile with the provider before taking the next safe action. Advanced outbox patterns are optional; the failure window is not.'),
q('H1','Choose the test layer','Which test best demonstrates a real database foreign-key constraint?',[
['A unit test mocking the repository','The mock may accept invalid states.'],['An integration test against the database','Exercises the actual constraint.',true],['A screenshot of a table','Does not execute the behaviour.']], 'Use unit tests for logic and integration tests for the contract with real infrastructure.','Which dependency must be real to establish this property?'),
q('H2','Find the missing security test','The suite checks anonymous rejection and owner success for order history. What is missing?',[
['Another authenticated customer requesting the same order','This exposes object-level access flaws.',true],['Only a different background colour','Unrelated to access control.'],['Another success test with the same owner','Does not exercise the missing boundary.']], 'Two authenticated identities are necessary to expose many object-access bugs.','Logged in is not the same as authorised.'),
q('H3','Boundary cases','Quantity must be an integer from 1 to 10. Which cases add useful boundary evidence?',[
['0 and 1','Checks just outside and at the lower boundary.',true],['10 and 11','Checks at and just outside the upper boundary.',true],['Only 5 repeated ten times','Repeated middle values add little boundary evidence.'],['1.5','Checks the integer constraint.',true]], 'Choose cases for specific rules rather than inflating the test count.','Find each edge of the valid set.','multi'),
match('H4','Test purpose','Match the test to the evidence it provides.',[['Unit total calculation','Arithmetic for a line in isolation'],['Database integration test','Actual persistence constraints and query behaviour'],['End-to-end checkout','The assembled user journey works'],['Manual keyboard review','Focus and task usability beyond an automated scan']], 'No one layer replaces all the others.'),
open('H5','Write the missing acceptance test','Write a Given / When / Then test for changing a product price after an order.',['Establish an original agreed unit price','Change the current catalogue price','Read the historical order','Assert original unit price and quantity-derived total'],'Given two units purchased at DKK 500, when the catalogue price becomes DKK 600, then the old order still shows DKK 500 per unit and DKK 1,000 total.'),
q('H6','Operational readiness','Which evidence belongs in a launch review?',[
['A tested restore procedure and named owner','Backup recovery must be executable.',true],['Monitoring of unresolved payment attempts','Helps detect customer-affecting failures.',true],['All secrets printed in logs for convenience','Exposes sensitive information.'],['Keyboard completion of core flows','Accessibility affects actual use.',true]], 'Readiness combines behaviour, protection, recovery and ownership.','What happens when a real customer encounters a failure?','multi'),
q('I1','Find the vertical slice','Which backlog item is a vertical slice?',[
['Create every table for the whole product','This completes one layer without a usable outcome.'],['Let staff view a basic order list from stored data through the UI','Crosses the necessary layers for one outcome.',true],['Style every button before adding behaviour','Delays validating the core flow.']], 'A small complete path produces earlier feedback and exposes integration problems.','Can someone achieve a useful task at the end?'),
q('I2','Investigate risk early','The legacy payment integration is poorly documented. When should you investigate it?',[
['At the end, after all screens','A late discovery can invalidate the plan.'],['Early with a focused feasibility investigation','Reduce uncertainty before committing detailed scope.',true],['Never; estimates will absorb it','An estimate does not establish feasibility.']], 'A spike should answer a concrete question and change the plan if necessary.','Which unknown could overturn your design?'),
q('I3','Agile and Scrum','Which statement is accurate?',[
['Scrum and agile are identical','Scrum is one framework within a broader family of adaptive approaches.'],['Agile can use approaches other than Scrum','The method should fit the context.',true],['Agile means no planning or documentation','Planning and communication still matter.']], 'Explain the feedback and adaptation mechanism, not just a ceremony name.','Separate a framework from the broader approach.'),
q('I4','A shorter deadline','Six weeks become four. Which response best protects delivery?',[
['Remove all testing and hope','This hides risk rather than managing scope.'],['Agree a smaller coherent release and retain essential quality','Make the scope/time/quality tradeoff explicit.',true],['Promise the original scope without revisiting assumptions','An unchanged promise is not a plan.']], 'Discuss what can be deferred, dependencies and consequences with the customer.','Protect the critical end-to-end outcome.','choice','scenario'),
order('I5','A launch dependency chain','Order this migration fixture. These steps have explicit dependencies.',['Agree source-to-target mapping and acceptance checks','Rehearse migration in a safe environment','Resolve discrepancies and obtain acceptance','Perform controlled production migration and verify results'],'Training, support planning and other work can run in parallel; this exercise tests the stated migration dependency chain.'),
open('I6','Compare delivery approaches','For an uncertain new product with a fixed contractual launch gate, propose an approach.',['Use early discovery and risk reduction','Include iterative customer demonstrations','Respect the required acceptance gate','Describe how scope changes are agreed','Name launch and support responsibilities'],'A hybrid can combine iterative implementation and feedback with formal launch acceptance. Explain the fit rather than treating one method as always superior.'),
open('J1','Your introduction','Give a 60–90-second introduction using only your actual background and experience.',['State current MSc and ML focus accurately','Connect relevant professional experience','Add only a real example if available','Use your own motivation rather than an invented reason'],'A clear introduction is a route into a conversation, not a full CV recital. The timer is optional and has no pass threshold.',true),
open('J2','Motivation with substance','Explain why this role interests you. Use only reasons you genuinely hold and facts you have verified.',['Name an actual interest','Connect it to a known aspect of the role','Avoid unsupported employer claims','Include a question you want to explore'],'There is no single right motivation. Specific and truthful reasoning is more useful than a generic compliment.',true),
open('J3','Your contribution','Prepare one real STAR story about collaboration.',['Brief situation and task','Specific actions you personally took','How you involved other people','Observed outcome without fabricated metrics','What you learned'],'Use “I” for your actions and “we” for collective results. If an outcome is qualitative, say so.'),
q('J4','An unfamiliar technology','You are asked about a tool you have not used. Which opening is strongest?',[
['Pretend to know it and use buzzwords','This makes reasoning and later clarification harder.'],['Say what you do know, label a hypothesis and propose how to investigate','Shows honest boundaries and a useful next step.',true],['Say only “I don’t know” and stop','Honest but misses a chance to reason from fundamentals.']], 'You can be candid about a gap and still contribute structure.','Distinguish knowledge from a provisional hypothesis.'),
open('J5','Switch the audience','Explain idempotent payment handling first to a customer and then a technical colleague.',['Customer explanation focuses on avoiding repeated charges','Technical explanation names stable operation identity','Acknowledge uncertainty after timeouts','Avoid claiming every provider behaves identically'],'Customer: “We recognise a repeated attempt so you do not accidentally pay twice.” Colleague: explain the provider contract, request fingerprint and reconciliation.',true),
q('J6','Receive a correction','Kasper says your diagram assumes a rule the customer does not want. What next?',[
['Defend the drawing because you already spent time on it','Sunk effort should not override a clarified need.'],['Acknowledge the correction, revise the assumption and explain affected artefacts','Makes adaptation collaborative and visible.',true],['Change the drawing without explaining anything','The interviewer loses access to your reasoning.']], 'Course correction can demonstrate strong consulting judgment.','Keep the customer involved in the revised decision.','choice','scenario')
];
export const diagnosticIds=['A1','B1','C2','D1','E3','F3','G3','H2','I1','J4'];
