import type { Attribute, Entity, Finding, ModelDoc } from './types';
export const uid=()=>crypto.randomUUID();
const attr=(name:string,key=false,type='text'):Attribute=>({id:uid(),name,key,type,nullable:false,unique:key});
const entity=(id:string,name:string,x:number,y:number,attrs:Attribute[]):Entity=>({id,name,concept:name,x,y,attributes:attrs});
export function starterModel(blank=false):ModelDoc{return {kind:'model',notation:'uml',submitted:true,assumptions:'Submitted orders have at least one line. Each line references one product. Orders retain agreed prices.',entities:blank?[]:[entity('order','Order',40,80,[attr('id',true,'uuid'),attr('currency')]),entity('line','OrderLine',370,80,[attr('id',true,'uuid'),attr('quantity',false,'integer')]),entity('product','Product',700,80,[attr('id',true,'uuid'),attr('currentPriceMinor',false,'integer')])],relationships:blank?[]:[{id:'ol',a:'order',b:'line',atA:'1',atB:'1',label:'contains'},{id:'lp',a:'line',b:'product',atA:'0..*',atB:'1',label:'refers to'}]};}
export function referenceModel():ModelDoc{const m=starterModel();m.relationships[0].atB='1..*';m.entities[1].attributes.push(attr('unitPriceMinor',false,'integer'));return m;}
export function validateModel(m:ModelDoc,webshop=true):Finding[]{const out:Finding[]=[];for(const e of m.entities){out.push({id:e.id+'key',kind:'objective',ok:e.attributes.some(a=>a.key&&!a.nullable),title:`${e.name}: identifier`,why:'A primary key identifies each row and must not be nullable.',hint:'Mark a suitable stable identifier as a key.'}); if(new Set(e.attributes.map(a=>a.name.toLowerCase())).size!==e.attributes.length)out.push({id:e.id+'names',kind:'objective',ok:false,title:`${e.name}: repeated attribute`,why:'Two fields with the same name are ambiguous.',hint:'Rename or remove the duplicate.'});}
for(const r of m.relationships)if(!m.entities.some(e=>e.id===r.a)||!m.entities.some(e=>e.id===r.b))out.push({id:r.id,kind:'objective',ok:false,title:'Broken relationship',why:'An endpoint references an entity that is not present.',hint:'Reconnect it to existing entities.'});
if(webshop){const o=m.entities.find(e=>e.concept==='Order'),l=m.entities.find(e=>e.concept==='OrderLine'),p=m.entities.find(e=>e.concept==='Product');const r=m.relationships.find(r=>o&&l&&((r.a===o.id&&r.b===l.id)||(r.b===o.id&&r.a===l.id)));const lineEnd=r?(r.b===l?.id?r.atB:r.atA):undefined,orderEnd=r?(r.a===o?.id?r.atA:r.atB):undefined;
out.push({id:'line-role',kind:'scenario',ok:!!l,title:'Represent each purchased product occurrence',why:'OrderLine holds quantity and agreed price for a product in a particular order. One product can occur in many orders.',hint:'Add an entity and map its concept to OrderLine.'});
out.push({id:'order-lines',kind:'scenario',ok:!!r&&orderEnd==='1'&&lineEnd===(m.submitted?'1..*':'0..*'),title:'Read both ends of Order — OrderLine',why:lineEnd==='1'?'The 1 beside OrderLine means each order can contain exactly one line. A tent and boots in one order are a counterexample. Each line can correctly belong to one order; keep that end at 1.':`For this declared ${m.submitted?'submitted-order':'draft-inclusive'} model: one order has ${m.submitted?'one or more':'zero or more'} lines; one line belongs to exactly one order.`,hint:`Set the endpoint beside OrderLine to ${m.submitted?'1..*':'0..*'} and the endpoint beside Order to 1. A NOT NULL foreign key alone does not enforce the parent’s minimum line count.`});
out.push({id:'price-snapshot',kind:'scenario',ok:!!l?.attributes.some(a=>/unitPriceMinor|agreedPrice|pricePaid/i.test(a.name)),title:'Preserve the agreed price',why:'Current product price can change. Historical orders need a price snapshot with a defined currency and monetary representation.',hint:'Add unitPriceMinor to OrderLine. Alternative names can be explained in your assumptions; this check recognises the listed field conventions only.'});
out.push({id:'product-link',kind:'scenario',ok:!!p&&!!l&&m.relationships.some(r=>r.a===l.id&&r.b===p.id&&r.atB==='1'&&r.atA.includes('*')||r.b===l.id&&r.a===p.id&&r.atA==='1'&&r.atB.includes('*')),title:'Connect lines to products',why:'In this fixture, each line refers to one product, while a product may occur on many lines.',hint:'Use a one-to-many relationship and read it in both directions.'});}
return out;}
export function tableProjection(m:ModelDoc){const tables=m.entities.map(e=>({id:e.id,name:e.name,columns:e.attributes.map(a=>`${a.name}: ${a.type}${a.key?' PRIMARY KEY':''}${!a.nullable?' NOT NULL':''}${a.unique&&!a.key?' UNIQUE':''}`),notes:[] as string[]}));for(const r of m.relationships){const a=tables.find(t=>t.id===r.a),b=tables.find(t=>t.id===r.b);if(!a||!b)continue;const am=r.atA.includes('*'),bm=r.atB.includes('*');if(am&&bm){tables.push({id:r.id,name:`${a.name}_${b.name}`,columns:[`${a.name.toLowerCase()}_id FOREIGN KEY → ${a.name}`,`${b.name.toLowerCase()}_id FOREIGN KEY → ${b.name}`],notes:['Associative table: choose an identifier and pair uniqueness according to the business rule. Add relationship attributes here.']});}else if(am||bm){const child=am?a:b,parent=am?b:a,parentMult=am?r.atB:r.atA;child.columns.push(`${parent.name.toLowerCase()}_id FOREIGN KEY → ${parent.name}${parentMult==='1'?' NOT NULL':' NULL allowed'}`);parent.notes.push('Child foreign keys do not enforce a minimum number of children.');}else{b.columns.push(`${a.name.toLowerCase()}_id FOREIGN KEY → ${a.name} UNIQUE${r.atA==='1'?' NOT NULL':' NULL allowed'}`);b.notes.push('One-to-one mapping shown on this side as an explicit projection choice. Reverse ownership may be valid; mandatory participation of the other side needs a separate rule.');}}return tables;}
