export interface Frame {title:string;action:string;component:string;db:string;provider:string;user:string;transaction:string;boundary:boolean}
export const scenarios=[['success','Successful checkout'],['race','Two customers, last item'],['duplicate','Duplicate submit'],['timeout-before','Timeout before provider accepts'],['timeout-after','Payment succeeds, response lost'],['local-failure','Payment succeeds, local write fails'],['webhook','Duplicate webhook delivery'],['declined','Payment declined']] as const;
export function simulate(scenario:string):Frame[]{const f=(title:string,action:string,component:string,db:string,provider:string,user:string,transaction='No open transaction',boundary=false):Frame=>({title,action,component,db,provider,user,transaction,boundary});const frames=[f('1 · Validate & authorise','The server checks identity, quantity, trusted price and permission. Browser validation is only a convenience.','backend','Stock: 1 · Orders: 0','No payment','Submitting'),f('2 · Reserve locally','Atomic conditional decrement and pending order are committed together. A durable operation identity is recorded.','database','Stock: 0 · Order: pending · Key: k-1','No payment','Submitting','Local transaction A: reserve + record → COMMIT')];
if(scenario==='race')frames.push(f('3 · Competing customer','A second conditional reservation affects zero rows. It cannot also obtain the last item.','database','Stock: 0 · Orders: 1','No payment','Second customer: item unavailable','Local transaction B: no reservation; no second order'));
if(scenario==='duplicate')frames.push(f('3 · Recognise repeated intent','The same customer and key k-1 with the same payload resolves to the existing order. Changed parameters would conflict.','backend','Stock: 0 · Orders: 1','No additional call','Existing order: pending'));
if(scenario==='timeout-before'){frames.push(f('3 · Timeout before acceptance','In this fixture the provider did not accept the call. The application only observes a timeout and cannot infer that fact yet.','provider','Order: pending · Payment: unknown','No payment recorded','Checking payment status','No open transaction',true));frames.push(f('4 · Reconcile and retry same operation','A provider lookup and supported retry with k-1 safely identify the operation. Do not create new intent.','provider','Order: pending','k-1: succeeded · Charges: 1','Checking payment status','No open transaction',true));}
else if(scenario==='declined'){frames.push(f('3 · Provider declines','The provider confirms a definitive failure for this operation. This differs from an unknown timeout.','provider','Order: pending','k-1: declined · Charges: 0','Payment declined','No open transaction',true));frames.push(f('4 · Record and release','This fixture releases the reservation after the confirmed decline. A new attempt would need its own explicit intent.','database','Stock: 1 · Order: payment failed','Declined','Choose another method or retry','Local transaction B: record failure + release → COMMIT'));return frames;}
else frames.push(f('3 · Call external provider','The local reservation is already committed. The provider has a separate durable ledger.','provider','Stock: 0 · Order: pending','k-1: succeeded · Charges: 1','Submitting','No open transaction',true));
if(scenario==='timeout-after')frames.push(f('4 · Lose the response','Payment succeeded remotely, but the service sees a timeout. Unknown describes knowledge, not a confirmed failure.','backend','Order: pending · Payment: unknown','k-1: succeeded · Charges: 1','Checking payment status'));
if(scenario==='local-failure')frames.push(f('4 · Local result write fails','The second local transaction rolls back. It cannot roll back the successful external payment.','database','Order: pending · Payment: unknown','k-1: succeeded · Charges: 1','Checking payment status','Local transaction B: ROLLBACK; reservation from A remains'));
if(['timeout-after','local-failure'].includes(scenario))frames.push(f('5 · Discover the existing result','Lookup/reconciliation for k-1 finds the existing success. Monitoring and a recovery owner are required for stuck operations.','provider','Order: pending','k-1: succeeded · Charges: 1','Checking payment status','No open transaction',true));
frames.push(f('Record known outcome','Store confirmed payment state. The historical price remains the price agreed before the provider call.','database','Stock: 0 · Order: paid · Orders: 1','k-1: succeeded · Charges: 1','Order confirmed','Local transaction: record result → COMMIT'));
if(scenario==='webhook')frames.push(f('Deduplicate a notification','The verified event ID was already processed. Recording the event and applying its transition atomically prevents a second effect.','backend','Order: paid · Applied event: evt-1 once','Charges: 1 · Duplicate event delivered','Order confirmed'));
return frames;}
export interface ApiState {stock:number;price:number;orders:{id:string;owner:string;quantity:number;unitPriceMinor:number;status:string}[];keys:Record<string,{fingerprint:string;orderId:string}>;events:string[]}
export const initialApi=():ApiState=>({stock:3,price:50000,orders:[{id:'o-1',owner:'customer-1',quantity:2,unitPriceMinor:50000,status:'paid'}],keys:{},events:[]});
export interface ApiRequest {method:string;path:string;body:string;identity:string;key:string;signature:string}
export function apiRequest(prev:ApiState,req:ApiRequest){const state=structuredClone(prev);const trace:string[]=[];const reply=(status:number,body:unknown)=>({status,body,state,trace,headers:{'Content-Type':'application/json'}});const url=new URL(req.path,'https://fixture.invalid');const path=url.pathname;let body:Record<string,unknown>={};if(req.body.trim()){try{const raw=JSON.parse(req.body);if(!raw||typeof raw!=='object'||Array.isArray(raw))return reply(400,{error:'Expected a JSON object'});body=raw;}catch{return reply(400,{error:'Malformed JSON'});}}
if(req.method==='GET'&&path==='/api/products'){const page=Number(url.searchParams.get('page')??1);if(!Number.isInteger(page)||page<1)return reply(422,{error:'page must be a positive integer'});const category=url.searchParams.get('category');return reply(200,{items:page===1&&(!category||category==='camping')?[{id:'p-1',name:'Trail tent',category:'camping',priceMinor:state.price,currency:'DKK',available:state.stock}]:[],page,pageSize:10,nextPage:null});}
if(req.method==='GET'&&path==='/api/products/p-1')return reply(200,{id:'p-1',name:'Trail tent',priceMinor:state.price,currency:'DKK',available:state.stock});
if(req.method==='POST'&&path==='/api/webhooks/payment'){trace.push('External boundary: verify declared fixture signature');if(req.signature!=='fixture-valid')return reply(401,{error:'Invalid fixture signature; production requires provider cryptographic verification'});if(typeof body.eventId!=='string'||typeof body.orderId!=='string'||!['paid','failed'].includes(String(body.status)))return reply(422,{error:'eventId, orderId and status paid|failed required'});if(state.events.includes(body.eventId))return reply(200,{duplicate:true});const o=state.orders.find(o=>o.id===body.orderId);if(!o)return reply(404,{error:'Order not found'});state.events.push(body.eventId);if(o.status!=='paid')o.status=String(body.status);trace.push('Local transaction: event deduplication and allowed state transition');return reply(200,{accepted:true,status:o.status});}
if(req.identity==='anonymous')return reply(401,{error:'Authentication required'});trace.push(`Authenticated as ${req.identity}`);
if(req.method==='GET'&&path.startsWith('/api/orders/')){const o=state.orders.find(o=>o.id===path.split('/').at(-1));trace.push('Object-level access check before returning data');if(!o||(req.identity!=='staff'&&o.owner!==req.identity))return reply(404,{error:'Order not found'});return reply(200,{...o,currency:'DKK',totalMinor:o.quantity*o.unitPriceMinor});}
if(req.method==='PATCH'&&path==='/api/products/p-1'){if(req.identity!=='staff')return reply(403,{error:'Staff role required'});if(!Number.isSafeInteger(body.priceMinor)||Number(body.priceMinor)<0)return reply(422,{error:'priceMinor must be a nonnegative safe integer'});state.price=Number(body.priceMinor);trace.push('Change current price; historical snapshots untouched');return reply(200,{priceMinor:state.price});}
if(req.method==='GET'&&path==='/api/payments'){if(req.identity!=='staff')return reply(403,{error:'Staff role required'});return reply(200,{attempts:state.orders.map(o=>({orderId:o.id,status:o.status}))});}
if(req.method==='POST'&&path==='/api/orders'){if(!req.key.trim())return reply(422,{error:'Idempotency-Key required by this fixture'});if(body.productId!=='p-1'||!Number.isInteger(body.quantity)||Number(body.quantity)<1||Number(body.quantity)>10)return reply(422,{error:'Use productId p-1 and integer quantity 1–10'});const fingerprint=JSON.stringify({productId:body.productId,quantity:body.quantity});const key=req.identity+':'+req.key;const existing=state.keys[key];if(existing){if(existing.fingerprint!==fingerprint)return reply(409,{error:'Key already used for different parameters'});trace.push('Same intent: return existing result without reserving again');return reply(200,{...state.orders.find(o=>o.id===existing.orderId),replayed:true});}if(Number(body.quantity)>state.stock)return reply(409,{error:'Insufficient stock; basket can be corrected'});const order={id:'o-'+(state.orders.length+1),owner:req.identity,quantity:Number(body.quantity),unitPriceMinor:state.price,status:'pending'};state.stock-=order.quantity;state.orders.push(order);state.keys[key]={fingerprint,orderId:order.id};trace.push('Trusted server price snapshot','Atomic local transaction: reserve + order + operation key','Payment is pending; this endpoint does not invent an external outcome');return reply(201,order);}
return reply(404,{error:'No fixture endpoint matches this request'});
}
