"""Reviewed educational annotations. All source references use physical PDF pages.
This is a transparent authoring file, not an automatic scientific summarizer.
Run this, then extract.py, then validate.py to regenerate the atlas data.
"""
import json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
papers=[]; crops=[]
def source(page,label): return dict(page=page,label=label)
def claim(text,page,label,kind='Paper evidence'): return dict(text=text,source=source(page,label),kind=kind)
def stage(label,enters,action,why,leaves,page,ref,status='Learned component'):
 return dict(label=label,input=enters,action=action,why=why,output=leaves,source=source(page,ref),status=status)
def result(metric,dataset,baseline,before,after,direction,page,ref,note,proposed=None):
 return dict(metric=metric,dataset=dataset,baseline=baseline,before=before,after=after,direction=direction,source=source(page,ref),note=note,proposed=proposed)
def equation(title,latex,symbols,plain,why,page,ref): return dict(title=title,latex=latex,symbols=symbols,plain=plain,why=why,source=source(page,ref))
def q(level,question,hint,answer,page,ref):return dict(level=level,question=question,hint=hint,answer=answer,source=source(page,ref))
def dim(id,role,text,page,ref):return dict(id=id,role=role,text=text,source=source(page,ref))
def compare(**kwargs):return {k:claim(v[0],v[1],v[2]) for k,v in kwargs.items()}
def fig(p,id,page,num,bounds,prefix,purpose,look,conclusion,main=False):
 crops.append(dict(paper=p['id'],sourcePdf=p['filename'],id=id,page=page,figure=num,bounds=bounds,captionPrefix=prefix,purpose=purpose,look=look,conclusion=conclusion,main=main))
def finish(p):
 p['questions']=[q('Basic',f"What problem does {p['short']} address?",'Name the task and the obstacle, before naming the method.',p['problem']['text'],p['problem']['source']['page'],p['problem']['source']['label']),q('Basic',f"What is the central idea of {p['short']}?",'Try explaining it without an acronym.',p['sentence']['text'],p['sentence']['source']['page'],p['sentence']['source']['label']),q('Basic',f"What goes in and what comes out of {p['short']}?",'Distinguish the deployment inputs from training supervision.',p['io']['text'],p['io']['source']['page'],p['io']['source']['label'])]+p['questions']
 papers.append(p)

p=dict(id='transferability',short='Transferability',number='01',filename='ECCV26_01_Transferability.pdf',title='Transferability Between Understanding and Generation in Unified Multimodal Models',category='Multimodal learning',task='Capability transfer in unified models',color='#b3a2de',position=[100,105],concepts=['multimodal','transfer','latent','diffusion'],
 sentence=claim('Teach a unified model to understand a visual skill, and that skill can improve its image generation too.',2,'Introduction'),
 problem=claim('A model can both understand and generate images without sharing useful capabilities between those tasks. Aggregate benchmark gains do not tell us whether teaching counting in one task actually improves counting in the other.',2,'Introduction'),
 core=[claim('The authors fine-tune only one task at a time, then test the same capability on the other. Four existing model families vary in how much of their transformer and visual encoding pathway is shared. Lumina-DiMOO, with a shared transformer and unified encoder, shows the strongest bidirectional counting transfer in this comparison.',5,'Fig. 1 & Table 1'),claim('They then exploit this effect: fine-tune understanding on skill-specific examples while keeping image generation as the test task. This can preserve the original visual distribution better than direct generation fine-tuning. The three probes are counting, diagonal spatial relations, and text recognition/generation; their gains differ.',8,'Sec. 4; Tables 2–4 on pp. 8–11')],
 io=claim('Training uses capability-specific image/question/answer examples (or image–caption pairs in the generation control). At generation inference, a text prompt enters the adapted unified model and an image comes out.',5,'Sec. 3.1; continuation p. 6'),
 why=claim('Sharing the representation gives an update learned through one objective a route to affect the other task. This is the authors’ interpretation of comparative experiments, not a proof that architectural sharing alone causes transfer.',7,'Sec. 3.2','Authors’ interpretation'),
 caution=claim('Architectural sharing is associated with stronger transfer here; it is not a universal guarantee. Even separately structured BAGEL and BLIP3-o improve understanding-to-generation counting in Table 1.',5,'Table 1'),
 novelty=[claim('A capability-matched intervention: train one task and test the same skill on the other, rather than infer transfer from aggregate scores.',2,'Introduction'),claim('An empirical comparison of transfer across four degrees of architectural coupling.',5,'Fig. 1 & Table 1'),claim('Understanding-only post-training as a practical way to improve generation while limiting distribution shift.',8,'Sec. 4')],
 existing=claim('Existing UMMs, visual tokenizers, transformers, autoregressive/diffusion generation, and LoRA are experimental machinery. The paper does not introduce a new image generator or sampler.',5,'Sec. 3.1'),
 stages=[stage('Skill examples','Images and count questions','Build matched understanding and generation training tasks.','Test a specific capability rather than a broad benchmark average.','VQA targets / image-caption control pairs',5,'Sec. 3.1','Training data'),stage('Frozen visual pathway','Input image','Encode images using the chosen pretrained UMM.','Keep the non-transformer components fixed in the intervention.','Visual tokens',25,'Appendix A','Frozen'),stage('Adapt the backbone','Visual tokens and question','Train LoRA in attention Q/K/V and MLP layers.','Concentrate the intervention in the shared transformer.','Updated adapter parameters',25,'Appendix A','Trained'),stage('Cross-task test','Generation prompt','Generate with the adapted model without generation supervision in this run.','Measure whether understanding updates transfer.','Generated image',6,'Sec. 3.1','Inference'),stage('Capability evaluation','Generated images','Check object count, layout, or OCR output; also assess distribution shift.','Skill accuracy and visual preservation are different outcomes.','Accuracy / MAD / OCR and distribution metrics',9,'Secs. 4.1–4.3','Evaluation only')],
 training=[claim('Select a pretrained UMM; construct one capability-specific dataset per run.',25,'Appendix A'),claim('Train rank-128 LoRA on transformer Q/K/V and MLP layers with the understanding objective. Separate control runs use generation supervision.',25,'Appendix A'),claim('Image encoder, projector/aligner, language-model head and diffusion head stay frozen.',25,'Appendix A')],
 inference=[claim('Supply a text-to-image prompt to the adapted UMM and use its original generation mechanism.',6,'Sec. 3.1'),claim('No VQA answers or counting annotations are supplied to generation. Detectors/OCR are used afterwards for evaluation.',6,'Sec. 3.1; p. 11 Sec. 4.3')],
 results=[result('Counting accuracy (%)','GenEval-style count prompts, Lumina-DiMOO','Pretrained baseline',48,57,'up',8,'Table 2','Direct generation training also obtains 57%; the accuracy alone does not distinguish the two strategies.'),result('FID to baseline outputs','Counting prompts, Lumina-DiMOO','Direct generation training',52.51,31.47,'down',8,'Table 2; definition p. 9','This FID measures shift from baseline-generated images, not distance to a real-image dataset.','Understanding → generation'),result('Spatial accuracy (%)','Synthetic diagonal-relation prompts','Direct generation training',80,74,'up',10,'Table 3','Understanding transfer has lower task accuracy here, although its FID to baseline is slightly lower.','Understanding → generation')],
 limitations=[claim('Only four representative architectural families are tested in the main analysis; architecture alone does not explain the direction or strength of transfer.',42,'Appendix E','Authors’ limitation'),claim('Text transfer is weaker on several measures, and the best direction cannot yet be predicted in advance.',42,'Appendix E','Authors’ limitation')],
 equations=[],equationNote='This paper’s key contribution is an experimental intervention, not a new mathematical objective. Read the architecture comparison and the train → test controls first.',
 dimensions=[dim('training','Enabling setup','LoRA adapts only part of the model. No end-to-end training speedup is established by the transfer results.',25,'Appendix A'),dim('generalization','Primary contribution','Cross-task capability transfer and preservation of the baseline generation distribution.',8,'Table 2')],
 takeaway='Shared machinery can make understanding supervision useful for generation; the strength depends on the skill.',
 comparison=compare(domain=('General image understanding and generation',1,'Abstract'),architecture=('Four 7B–8B UMMs: Lumina-DiMOO, Janus-Pro, BAGEL, BLIP3-o',5,'Sec. 3.1'),objective=('Task-specific LoRA supervised fine-tuning; separate understanding and generation runs',25,'Appendix A'),generative=('Existing autoregressive and discrete/continuous diffusion UMMs',3,'Sec. 2.1'),flow=('Diffusion is part of existing UMMs; no new flow sampler',3,'Sec. 2.1'),frequency=('No wavelet method introduced',3,'Sec. 2.1'),trainingCost=('LoRA rank 128, frozen non-backbone components; speedup not reported',25,'Appendix A'),inferenceCost=('Original UMM generation procedure; inference speedup not reported',6,'Sec. 3.1'),supervision=('Counting VQA; synthetic spatial and rendered-text examples',9,'Secs. 4.2–4.3'),modality=('Not a medical-imaging study',1,'Abstract'),datasets=('PixMo-Points/Count; ImageNet-derived spatial pairs; rendered Markdown text',5,'Sec. 3.1; pp. 9, 11'),metrics=('Accuracy, MAD, IS, FID to baseline; OCR WER/CER and text metrics',8,'Tables 2–4')),
 questions=[q('Method','Which parameters are adapted, and which stay frozen?','The intervention is centered on the transformer.','LoRA is trained in attention Q/K/V and MLP layers. Image encoder, projector/aligner, language modeling head, and diffusion head are frozen.',25,'Appendix A'),q('Method','What does the FID in the counting experiment measure?','Check which distribution acts as the reference.','It compares images from a fine-tuned model with images generated by the baseline. It measures distribution shift here, not real-data fidelity.',9,'Sec. 4.1'),q('Method','Does every architecture show bidirectional counting transfer?','Compare both halves of Table 1.','No. Lumina-DiMOO is strongest in both directions. Janus-Pro loses generation accuracy after understanding training; the two directions are not interchangeable.',5,'Table 1'),q('Reasoning','Why is a higher generation score insufficient to prove cross-task transfer?','Ask what was trained and what was tested.','A gain could come from direct generation supervision or unrelated extra data. The matched-capability intervention trains only the other task before measuring that capability.',2,'Introduction'),q('Reasoning','How does this differ from changing a tokenizer, as in DeBaT?','Locate the intervention in the pipeline.','Here pretrained UMM backbones are adapted through a different task objective while the visual encoder stays frozen. DeBaT changes how visual detail is encoded; it is a representation-learning intervention.',25,'Appendix A')])
fig(p,'architecture',5,'Figure 1',[132,112,484,232],'Fig. 1:','Compare routes for sharing knowledge','Follow which encoder and transformer are shared across tasks.','Lumina-DiMOO is the fully shared configuration tested; the drawing alone is not evidence of transfer.',True)
fig(p,'counting',8,'Figure 3',[132,112,484,282],'Fig. 3:','Separate skill accuracy from visual quality','Compare the same prompts across baseline, understanding transfer, and direct generation.','The examples illustrate preservation of visual style; use Table 2 for aggregate performance.')
fig(p,'spatial',10,'Figure 5',[132,112,484,284],'Fig. 5:','See the distribution-shift trade-off','Look for pasted-object appearance in the direct generation column.','Transfer and direct fine-tuning have different quality/accuracy trade-offs, not a universal winner.')
finish(p)

p=dict(id='sphere',short='SPHERE',number='02',filename='ECCV26_02_SPHERE.pdf',title='SPHERE: From MRI Sampling Mechanisms to Spatial Priors for Generalizable Brain Tumor Segmentation',category='Generalization',task='Brain tumor MRI segmentation',color='#8cbdac',position=[900,385],concepts=['mri','segmentation','kspace','dvf','generalization','physics'],
 sentence=claim('Estimate how an MRI was sampled, turn that estimate into a spatial prior, and use it to guide tumor segmentation.',1,'Abstract'),
 problem=claim('MRI acquisition changes which spatial frequencies survive reconstruction. Segmentation models trained only on image appearance can be brittle across scanners, while common segmentation datasets lack the original sampling metadata.',2,'Introduction'),
 core=[claim('SPHERE-Recover learns from reconstructed images paired with DICOM acquisition metadata. A spatial ViT branch and an FFT-based frequency branch predict sampling dimensions, ratios, and direction. This lets the method estimate sampling-related parameters when headers are unavailable.',6,'Sec. 3.1'),claim('The estimated parameters define a simulated sampling operator. Comparing the original and perturbed image yields a smooth deformation vector field (DVF). SPHERE-Seg uses this field to align features and modulate retention in its Swin-RetNet encoder–decoder.',7,'Secs. 3.2–3.3')],
 io=claim('Reconstructed MRI enters parameter recovery and DVF preprocessing; MRI plus DVF enter SPHERE-Seg; tumor-region masks come out. DICOM metadata supervises recovery training but is not required at deployment.',9,'Sec. 3.3; p. 14 complexity'),
 why=claim('A spatially organized prior can tell the segmentation network where acquisition-related perturbations affect structure. Shuffling DVFs worsens performance, supporting the value of their spatial organization.',12,'Sec. 4.5'),
 caution=claim('The DVF is explicitly not an exact physical deformation caused by acquisition. “Sampling” here means MRI k-space acquisition, not drawing an image from a generative model.',7,'Sec. 3.2'),
 novelty=[claim('Recover sampling-related geometry from reconstructed MRI using spatial and frequency features.',6,'Sec. 3.1'),claim('Convert estimated acquisition conditions into a continuous, segmentation-relevant deformation prior.',7,'Sec. 3.2'),claim('Inject the DVF through feature warping and deformation-modulated retention in DPM.',8,'Sec. 3.3')],
 existing=claim('FFT, ViT features, U-shaped encoder–decoders, sliding-window attention, retention, and differentiable warping are building blocks. The recovery → DVF → segmentation linkage is the central contribution.',4,'Secs. 2.2–3'),
 stages=[stage('MRI image','Reconstructed MRI','Send the image to spatial and frequency feature branches.','Segmentation datasets often lack raw acquisition parameters.','ViT features and real/imaginary FFT features',6,'Sec. 3.1','Input'),stage('SPHERE-Recover','Spatial and frequency features','Concatenate features and predict acquisition parameters with an MLP.','Estimate missing sampling information from the image.','Estimated parameter vector',6,'Sec. 3.1','Preprocessing at inference'),stage('Construct DVF','Image and estimated sampling parameters','Simulate a sampled image and solve a smooth brightness-alignment problem.','Express the structural perturbation as a usable spatial field.','Continuous displacement field',7,'Sec. 3.2','Preprocessing at inference'),stage('DPM','Multiscale features and resized DVF','Warp features and modulate retention using deformation magnitude.','Align structure and guide information aggregation.','Updated features and aligned skip connections',8,'Sec. 3.3','Trained'),stage('Segmentation decoder','Enhanced multiscale features','Decode tumor-region predictions.','Produce the actual downstream output.','Tumor masks',5,'Fig. 3','Trained')],
 training=[claim('Train SPHERE-Recover on MRI BRP images with DICOM-derived parameters: regression MSE plus direction cross-entropy.',6,'Sec. 3.1; dataset p. 9'),claim('Train SPHERE-Seg with recovered DVFs and tumor masks on BraTS 2023. Segmentation loss weights Dice:BCE at 2:8.',10,'Sec. 4.2'),claim('Recovery and segmentation have separate supervision. The paper does not explicitly document a joint end-to-end freeze schedule.',6,'Sec. 3.1; p. 10 Sec. 4.2','Reading boundary')],
 inference=[claim('Recover parameters from the reconstructed MRI and generate the DVF in preprocessing. No DICOM header is needed.',9,'Sec. 3.3'),claim('SPHERE-Seg consumes the image and prepared DVF. Reported segmentation cost excludes the recovery preprocessing model.',14,'Complexity analysis')],
 results=[result('Average Dice (%)','BraTS 2019, trained on BraTS 2023','Base, no prior',89.79,91.27,'up',13,'Table 6','Cross-dataset ablation of the complete prior and fusion system.'),result('Average Dice (%)','BraTS 2023, in-domain','Base, no prior',92.25,92.87,'up',13,'Table 6','The in-domain gain is smaller than the cross-dataset gain.'),result('Parameters (M)','Segmentation models in reported comparison','Swin UNETR',25.11,14.88,'down',14,'Complexity analysis','SPHERE-Seg only. SPHERE-Recover and DVF preprocessing are not included in this count.')],
 limitations=[claim('The deformation field captures segmentation-relevant variations, rather than an exact acquisition-induced physical warp.',7,'Sec. 3.2','Authors’ qualification'),claim('Recovery supervision uses 351 MRI BRP slices; deployment still needs recovery and DVF preprocessing even though their cost is excluded from SPHERE-Seg figures.',9,'Table 2; p. 14','Scope of evidence')],
 equations=[equation('From sampling to an artifact map',r'\widetilde I=\mathcal F^{-1}(\mathcal M_\theta\odot\mathcal F(I)),\qquad A(\mathbf x)=|I(\mathbf x)-\widetilde I(\mathbf x)|',['I: reconstructed input MRI; Ĩ: simulated sampled image','ℱ and ℱ⁻¹: Fourier transform and inverse','ℳθ: sampling operator set by estimated parameters θ; ⊙: elementwise product','x: spatial position; A: artifact magnitude'],'Apply the estimated sampling pattern in frequency space, reconstruct, then compare the two images.','This constructs an acquisition-related disturbance before the smooth DVF is estimated. A is an intermediate, not the final DVF.',7,'Eqs. 10–11')],
 dimensions=[dim('backbone','Measured, scoped','14.88M parameters and 44.28G FLOPs for SPHERE-Seg; recovery preprocessing is excluded.',14,'Complexity analysis'),dim('generalization','Primary contribution','Train on BraTS 2023; evaluate also on BraTS 2019 and MSD.',14,'Table 7'),dim('medical','Application','MRI brain tumor segmentation with acquisition-aware structural priors.',1,'Abstract')],takeaway='Recover acquisition information, then use it as a spatial prior—not as literal tissue motion.',
 comparison=compare(domain=('Medical image segmentation',1,'Abstract'),architecture=('Spatial ViT + FFT recovery model; Swin-RetNet U-shaped segmenter with DPM',5,'Fig. 3'),objective=('Recovery: MSE + cross-entropy; segmentation: Dice + BCE, weights 2:8',6,'Sec. 3.1; p. 10 Sec. 4.2'),generative=('Not a generative model',5,'Fig. 3'),flow=('No generative flow or diffusion sampler; DVF is a structural prior',7,'Sec. 3.2'),frequency=('FFT and k-space sampling simulation, not a wavelet tokenizer',7,'Eq. 10'),trainingCost=('Separate recovery supervision; ImageNet-pretrained ViT, 300-epoch segmentation setup',10,'Sec. 4.2'),inferenceCost=('14.88M / 44.28G for SPHERE-Seg, excluding recovery preprocessing',14,'Complexity analysis'),supervision=('DICOM metadata for recovery; tumor masks for segmentation',9,'Sec. 4.1'),modality=('Brain MRI: T1, contrast-enhanced T1, T2, FLAIR',9,'Table 2'),datasets=('MRI BRP; BraTS 2019/2023; MSD Task01',9,'Table 2'),metrics=('Dice, HD95; sampling MAE; DVF consistency',10,'Sec. 4.3')),
 questions=[q('Method','Why predict acquisition parameters if a tumor mask is the output?','The intermediate is a spatial prior.','The parameters drive simulated sampling and a DVF. DPM uses that field to guide feature alignment and retention for segmentation.',5,'Fig. 3'),q('Method','Are DICOM headers needed at inference?','Separate supervision from deployment.','No. They supervise SPHERE-Recover during training; reconstructed images are sufficient for parameter recovery and DVF preprocessing at inference.',9,'Sec. 3.3'),q('Method','Is the DVF an exact physical deformation?','Read the explicit qualification in Sec. 3.2.','No. It captures segmentation-relevant structural perturbations; aliasing and blur are not necessarily literal spatial deformation.',7,'Sec. 3.2'),q('Reasoning','Does SPHERE accelerate the same sampling process as ParaFlow?','The word sampling has two meanings.','No. SPHERE models k-space acquisition sampling. ParaFlow parallelizes ODE steps of a pretrained generative model.',3,'Sec. 2.1'),q('Reasoning','Can you interpret the reported segmentation FLOPs as complete pipeline cost?','Look for the preprocessing exclusion.','No. The quoted 44.28G FLOPs belong to SPHERE-Seg; SPHERE-Recover runs in preprocessing to produce the prior.',14,'Complexity analysis')])
fig(p,'architecture',5,'Figure 3',[132,112,484,350],'Fig. 3:','Trace acquisition recovery into segmentation','Follow panels (a) recovery, (b) DVF construction, (c) segmentation, and (d) prior injection.','The predicted acquisition variables matter through the spatial prior used by DPM.',True)
fig(p,'dvf',7,'Figure 4',[185,112,430,194],'Fig. 4:','Understand what a DVF represents','Compare artifact magnitude, gradient energy, and vector directions.','These are different representations; the field is a structural proxy, not measured tissue movement.')
fig(p,'ablation',13,'Table 6',[132,113,484,340],'Table 6:','Test whether spatial organization matters','Compare Base, Shuffle-DVF, and SPHERE; paired values are BraTS 2023 / BraTS 2019.','An arbitrary extra field does not explain the gain: shuffled fields underperform the baseline.')
finish(p)
p=dict(id='pdf',short='PDF',number='03',filename='ECCV26_03_PhysicsGroundedFlow.pdf',title='Physics-Grounded Disentangled Flow Modeling for Brain Disease Progression Trajectory',category='Medical generation',task='Longitudinal brain MRI forecasting',color='#c9b07d',position=[510,385],concepts=['flow','mri','physics','fisher','pde','dvf','frequency','psnr','dice'],
 sentence=claim('Predict how a lesion changes shape first, then how the MRI appearance changes, with a soft physics constraint on lesion evolution.',2,'Introduction'),
 problem=claim('Directly predicting a future MRI entangles structural changes with intensity changes. Limited longitudinal data, irregular scan intervals, and protocol variation make that mapping difficult to interpret and generalize.',2,'Introduction'),
 core=[claim('Two flow-matching networks divide the work. The morphology network predicts lesion evolution conditioned on the baseline image and elapsed time. At inference, optical flow between baseline and predicted masks supplies a deformation field that warps the baseline image.',8,'Sec. 3.2; inference p. 9'),claim('The intensity network refines that warped image. During morphology training, a PDE-inspired penalty discourages velocity components outside a diffusion–reaction–advection span. The concentration maps used to form that span are smooth transforms of binary masks, not measured cell densities.',7,'Eqs. 11–13; map construction p. 10')],
 io=claim('Baseline MRI, its lesion mask, and the desired time interval enter the forecasting pipeline. It predicts an evolved lesion and a future MRI image. Follow-up images and masks are training supervision, not inference inputs.',9,'Inference'),
 why=claim('Separating geometry from intensity gives each network a simpler role. The physics penalty adds a preference for structured evolution rather than unconstrained changes. Ablations test the two components and the regularizer separately.',13,'Sec. 4.3; Table 3 p. 14'),
 caution=claim('The PDE is a regularization constraint, not an exact biological simulator embedded in the generator. Mask-derived concentration is a proxy; two flow models also add computation.',23,'Appendix E.1; map definition p. 10'),
 novelty=[claim('Separate morphology evolution and intensity evolution with dedicated flow-matching models.',8,'Sec. 3.2'),claim('Regularize morphology velocity using its residual after projection onto a diffusion–reaction–advection span.',7,'Eqs. 11–13'),claim('Compose predicted lesion motion, baseline-image warping, and appearance refinement into longitudinal forecasting.',9,'Inference')],
 existing=claim('U-Net backbones, flow matching, Fisher-KPP-inspired dynamics, TV-L1 optical flow, and image warping are reused. The contribution is their disentangled forecasting formulation and projection regularizer.',9,'Sec. 3.2; p. 10 Implementation'),
 stages=[stage('Baseline + horizon','Baseline image, lesion mask, and elapsed time','Condition the morphology model on anatomy and the requested interval.','Forecast progression from a known observation.','Morphological velocity',8,'Eq. 14','Trained'),stage('Lesion evolution','Morphological velocity','Integrate over the time interval to predict the future lesion.','Separate structural evolution from appearance.','Predicted lesion mask',9,'Inference','Inference'),stage('Structural warp','Baseline and predicted lesion masks','Estimate TV-L1 displacement, then warp the baseline image.','Move the structure before changing signal intensity.','Morphology-warped MRI',9,'Eqs. 20–21','Nonlearned optical flow'),stage('Intensity refinement','Warped image and baseline lesion conditioning','Integrate the learned intensity velocity.','Capture signal changes that a spatial warp cannot express.','Refined future image',9,'Inference','Trained'),stage('Texture preservation','Baseline lesion texture and refined image','Add high-frequency guidance extracted using Difference-of-Gaussians.','Preserve lesion-specific texture details.','Final predicted MRI',22,'Appendix D','Inference')],
 training=[claim('Use longitudinal image/mask pairs and their time interval. Convert masks through signed distance and sigmoid to concentration proxies.',8,'Sec. 3.2; p. 10 map construction'),claim('Fit diffusion/reaction terms and estimate transport to form the physics span. Train morphology with flow matching plus λ times projection-residual loss.',6,'Sec. 3.1.2; p. 8 Eq. 17'),claim('Train intensity flow in image space with a flow-matching objective conditioned on lesion information.',8,'Sec. 3.2; p. 9 Eq. 19')],
 inference=[claim('Require the baseline lesion mask as well as the baseline image and time interval. Predict the evolved lesion, estimate optical flow, and warp the image.',9,'Inference'),claim('Refine intensity and preserve baseline lesion texture. The PDE loss and follow-up ground truth are not inference inputs.',9,'Inference; p. 22 Appendix D')],
 results=[result('DSC','UCSF tumor progression','T-UNet',0.728,0.752,'up',12,'Table 1','Lesion-level agreement improves; the same comparison has a lower image PSNR.'),result('PSNR (dB)','UCSF tumor progression','T-UNet',31.739,31.364,'up',12,'Table 1','A counter-result: better lesion progression does not imply better whole-image PSNR.'),result('DSC','LMSLS, PDE regularizer ablation','Without PDE loss',0.690,0.696,'up',14,'Table 3','The controlled gain from the regularizer is modest; do not attribute all performance to physics.')],
 limitations=[claim('Baseline lesion masks are required; segmentation errors can propagate into both predicted morphology and future images.',23,'Appendix E.1','Authors’ limitation'),claim('Two separate flow models add overhead; the physics currently guides learning through a regularizer.',23,'Appendix E.1','Authors’ limitation'),claim('LUMIERE full-model PSNR differs between Table 1 (37.216) and the joint row of Table 2 (37.075). The atlas does not silently merge these values.',12,'Table 1; Table 2 p. 13','Source inconsistency')],
 equations=[equation('The physics-inspired dynamics',r'\frac{\partial c}{\partial t}=D\Delta c+\rho c(1-c)-\mathbf u\cdot\nabla c',['c(x,t): normalized lesion concentration proxy; x: location; t: time','D: diffusion coefficient; Δ: spatial Laplacian','ρ: reaction/proliferation rate; u: advection velocity field','∇: spatial gradient; ·: dot product'],'Spread out, grow locally, and move through space. These are three different ways the concentration can change.','These terms define the physics span used by the regularizer; the paper does not solve an exact patient-specific biological model at deployment.',5,'Eq. 2'),equation('Penalize what the physics span cannot explain',r'\mathcal L_{\mathrm{PDE}}=\|v_\theta-\Pi_{\mathcal S}(v_\theta)\|_2^2',['vθ: predicted morphology velocity; θ: learned network parameters','S: span of Δc, c(1−c), and −u·∇c evaluated using baseline quantities','ΠS: least-squares projection onto that span','‖·‖₂²: squared Euclidean norm'],'Project the prediction onto the three physics-inspired components, then penalize the part left over.','This is a soft preference for physics-compatible motion, not an equality constraint requiring exact PDE solutions.',7,'Eq. 13')],
 dimensions=[dim('medical','Primary contribution','Forecast longitudinal MRI progression across tumor and MS cohorts.',12,'Table 1'),dim('training','Added cost','Two flow models and a PDE projection regularizer; this is not demonstrated training acceleration.',23,'Appendix E.1')],takeaway='Move the lesion, then change the signal. Physics narrows the learned behavior without certifying biology.',
 comparison=compare(domain=('Longitudinal brain disease forecasting',1,'Abstract'),architecture=('Two U-Net flow-matching models plus TV-L1 optical flow and warping',9,'Sec. 3.2; p. 10 Implementation'),objective=('Morphology FM + λ PDE projection loss; intensity FM',8,'Eqs. 16–19'),generative=('Disentangled morphology and intensity flow matching',8,'Sec. 3.2'),flow=('Two learned flow fields; structural optical flow is a separate operation',9,'Inference'),frequency=('Difference-of-Gaussians baseline lesion-texture guidance; no Haar transform',22,'Appendix D'),trainingCost=('Two models add overhead; PDE terms fitted from paired observations',23,'Appendix E.1'),inferenceCost=('Morphology integration → optical-flow warp → intensity integration; speedup not reported',9,'Inference'),supervision=('Longitudinal image/mask pairs; baseline mask also needed at inference',8,'Sec. 3.2'),modality=('T1 / contrast-enhanced T1 / FLAIR MRI',10,'Datasets'),datasets=('UCSF-ALPTDG, LUMIERE, LMSLS',10,'Datasets'),metrics=('DSC, HD, PSNR, SSIM, L1; HD here is not HD95',10,'Evaluation metrics')),
 questions=[q('Method','What is the physics loss actually penalizing?','Think projection and residual.','The squared difference between predicted morphology velocity and its least-squares projection onto the diffusion–reaction–advection span.',7,'Eq. 13'),q('Method','Why is there optical flow after morphology prediction?','A lesion prediction is not yet a dense image warp.','Optical flow estimates a displacement aligning baseline and predicted lesion masks. That displacement warps the baseline MRI before intensity refinement.',9,'Eq. 20'),q('Method','What extra information is needed at inference?','The input is not just an MRI.','A baseline lesion mask and the desired time interval are required. Imperfect baseline masks are an acknowledged failure source.',23,'Appendix E.1'),q('Reasoning','Does a lower PSNR prove worse progression modeling?','Compare image-level and lesion-level measurements.','No. On UCSF, PDF has lower PSNR than T-UNet but higher DSC and lower HD. Small lesion changes can be diluted in whole-image measurements.',12,'Table 1 & interpretation'),q('Reasoning','Does the physics penalty make this an exact biological simulation?','Ask where the concentration and constraints come from.','No. Concentration is derived from masks and the PDE enters as a soft projection penalty. The authors explicitly describe the current dynamics as regularization.',23,'Appendix E.1')])
fig(p,'concept',2,'Figure 1',[132,112,484,291],'Fig. 1:','Separate morphology from appearance','Follow the two branches under the observed longitudinal series.','Shape evolution and intensity change are modeled as complementary processes.')
fig(p,'architecture',7,'Figure 3',[132,112,484,297],'Fig. 3:','Connect training losses to inference','Compare the training panels on top with the sequential deployment path below.','The PDE projection belongs to training; inference composes morphology, warp, and intensity.',True)
fig(p,'ablation',14,'Table 3',[132,228,495,322],'Table 3:','Measure the effect of the physics penalty','Compare with/without PDE rows across all three datasets.','The regularizer improves lesion metrics, but its incremental contribution is smaller than the complete method comparison.')
finish(p)

p=dict(id='drift',short='DRIFT',number='04',filename='ECCV26_04_DRIFT.pdf',title='DRIFT: Difficulty-aware Rectified Flows for Through-plane MRI Super-Resolution',category='Inference efficiency',task='Through-plane MRI super-resolution',color='#b8cc87',position=[900,105],concepts=['flow','rectified','ode','mri','thickness','frequency','nfe','psnr','ssim'],
 sentence=claim('First make a coarse sharp-slice MRI estimate, then spend only the flow-refinement steps justified by the input slice thickness.',4,'Fig. 1'),
 problem=claim('Thick-slice MRI loses through-plane detail. Fixed-scale models do not naturally handle continuous thickness changes, while iterative generative reconstruction can spend the same expensive step budget on both easy and hard inputs.',4,'Related work; p. 9 Sec. 3.6'),
 core=[claim('An Anatomical Projection Network (APN) learns a deterministic coarse reconstruction conditioned on input and target inverse slice thickness. Its output initializes a second, rectified-flow model. The second model learns the residual path toward the high-resolution target, rather than a path starting from random noise.',7,'Secs. 3.3–3.4'),claim('At inference, Physics-Aware Difficulty (PAD) converts the relative input/target thickness into a bandwidth-deficit cue. The Adaptive Integration Scheduler (AIS) uses that cue to choose an Euler-step budget. During training, CETA encourages nearby thickness conditions of the same anatomy to predict consistent endpoints.',8,'Sec. 3.5; p. 9 Sec. 3.6')],
 io=claim('A thick-slice MRI volume, its input thickness, and a target thickness enter the system. Deterministic slice-wise APN + rectified-flow predictions are assembled into a super-resolved volume.',5,'Sec. 3; conditioning p. 6'),
 why=claim('Starting from a stable anatomical estimate reduces the residual transport needed for detail recovery. Thickness is a metadata cue for missing bandwidth, so easier acquisitions need fewer refinements. Shared deterministic processing also encourages continuity across neighboring slices.',7,'Sec. 3.3; scheduler p. 9','Authors’ rationale'),
 caution=claim('PAD is a protocol-severity cue, not an image difficulty predictor. The main experiments fix each dataset’s target thickness; accepting a target embedding does not establish arbitrary target-resolution generalization.',6,'Sec. 3.2; p. 9 Sec. 3.6'),
 novelty=[claim('Specialize coarse-to-fine transport to through-plane MRI using SLR slice-profile degradation and inverse-thickness conditioning.',6,'Secs. 3.1–3.2'),claim('Allocate Euler steps directly from acquisition thickness using PAD and AIS, without an auxiliary difficulty network.',9,'Sec. 3.6'),claim('CETA aligns endpoint proxies for proximal thickness pairs from the same HR patch.',8,'Sec. 3.5')],
 existing=claim('Rectified flow, U-Net-style restoration, AdaGN, Euler integration, and the broad posterior-mean-to-image transport idea precede this work. The MRI acquisition-aware conditioning, scheduling, and endpoint regularization make DRIFT specific.',4,'Related work'),
 stages=[stage('Thickness conditioning','Input Ti and target Thr in mm','Encode inverse thicknesses using separate MLPs, then fuse them.','Represent the acquisition bandwidth conditions.','Conditioning vector ci',6,'Eq. 2','Metadata required'),stage('Anatomical projection','LR patch and thickness embedding','APN reconstructs a coarse, structurally consistent HR patch.','Provide a short residual path and deterministic slice initialization.','Coarse estimate z',7,'Eq. 4','Frozen in stage 2 training'),stage('PAD → AIS','Input and target thicknesses','Map relative bandwidth loss to 0–15 Euler steps.','Allocate more evaluations to thicker, harder inputs.','Step budget N',9,'Eqs. 13–14','Inference only'),stage('Rectified-flow refinement','z, time and thickness conditioning','Integrate the learned velocity from the APN estimate.','Recover fine details under the chosen budget.','Refined HR patch',7,'Sec. 3.4; p. 9','Trained'),stage('Volume assembly','Overlapping predicted patches/slices','Blend overlapping patches and compose the volume.','Apply the 2D operator across a full volume.','Super-resolved MRI',10,'Implementation','Inference')],
 training=[claim('Synthesize LR/HR pairs using an SLR-derived slice profile and random thickness/axis. Train APN with Charbonnier + 0.5 × SSIM loss.',6,'Sec. 3.1; p. 7 Eq. 5'),claim('Freeze APN. Interpolate between its output and HR target; train velocity with Huber regression and endpoint-biased time sampling.',7,'Sec. 3.4; p. 8 Eq. 9'),claim('Add CETA on neighboring thicknesses (1 mm gap); stage-2 loss is LRF + λceta LCETA. HR targets and paired thickness conditions are training-only.',8,'Sec. 3.5')],
 inference=[claim('Supply input and target thickness; run APN once to initialize the image state.',6,'Sec. 3.2; p. 7 Eq. 4'),claim('Compute PAD and the AIS budget, then integrate the rectified-flow velocity with Euler steps. No random-noise start, CETA loss, or HR target is used.',9,'Sec. 3.6'),claim('Blend sliding-window patches with 32-pixel overlap and compose slices into a 3D volume.',10,'Implementation')],
 results=[result('PSNR (dB)','HCP ×8, 5.6 → 0.7 mm','SwinIR',33.13,35.93,'up',12,'Table 1','Fixed-scale, retrained baseline comparison on simulated thick-slice data.'),result('SSIM','HCP ×8, 5.6 → 0.7 mm','SwinIR',0.882,0.936,'up',12,'Table 1','SSIM is averaged over slices in three directions; PSNR is measured over volumes.'),result('Velocity NFEs','HCP ×8, 5.6 → 0.7 mm','ResShift',15,13,'down',13,'Sec. 4.4 & Fig. 6 p. 14','This is stage-2 velocity NFE, not total pipeline computation. DRIFT also runs APN.')],
 limitations=[claim('Main experiments use fixed native target thicknesses; broader target-resolution and anatomy generalization remain future directions.',15,'Conclusion','Authors’ limitation'),claim('The real thick-slice evaluation has no isotropic ground truth. Visual sharpness and no-reference metrics cannot establish exact anatomical recovery.',12,'Sec. 4.3','Scope of evidence'),claim('The model processes 2D slices without explicit 3D convolution or cross-slice communication.',5,'Sec. 3','Architectural boundary')],
 equations=[equation('A residual path, not a noise path',r'\mathbf s_{p,i}(t)=(1-t)\mathbf z_{p,i}+t\mathbf y_p,\qquad\mathbf u_{p,i}=\mathbf y_p-\mathbf z_{p,i}',['p: patch index; i: input thickness condition; t ∈ [0,1]: interpolation time','z: coarse APN output; y: high-resolution target','s(t): intermediate image; u: constant target velocity'],'Draw a straight line from the APN prediction to the target, and learn the direction along that line.','The starting point already contains anatomy, so the network learns residual refinement rather than full synthesis.',7,'Eq. 6'),equation('Turn thickness into a step budget',r'\mathrm{PAD}=1-\frac{T_{\mathrm{hr}}}{T_i},\qquad N=\mathrm{clamp}\!\left(\mathrm{round}(N_{\max}\mathrm{PAD}),N_{\min},N_{\max}\right)',['Ti: input slice thickness; Thr: target thickness in the same units','PAD: normalized bandwidth-deficit cue; N: Euler steps / velocity NFEs','Nmin = 0 and Nmax = 15 in the main setting; clamp restricts the range'],'A larger thickness gap receives more refinement steps. Equal thickness permits zero refinement.','This is the actual metadata-only AIS rule. The interactive calculator below evaluates it, not the neural model.',9,'Eqs. 13–14')],
 dimensions=[dim('inference','Primary contribution','Short residual transport and thickness-adaptive ODE steps.',9,'Sec. 3.6'),dim('generalization','Evaluated, bounded','Continuous input thickness and zero-shot real thick-slice MRI; native target thickness mainly fixed.',12,'Secs. 4.2–4.3'),dim('medical','Application','Through-plane MRI super-resolution.',1,'Title')],takeaway='Start near the answer; use slice thickness to decide how much refinement is enough.',
 comparison=compare(domain=('Through-plane MRI super-resolution',5,'Sec. 3'),architecture=('2D APN followed by a thickness/time-conditioned rectified-flow velocity model',5,'Fig. 2'),objective=('APN: Charbonnier + SSIM; velocity: Huber RF + CETA',7,'Secs. 3.3–3.5'),generative=('Deterministic conditional rectified-flow refinement from APN output',4,'Fig. 1'),flow=('Rectified flow; AIS selects sequential Euler steps',9,'Sec. 3.6'),frequency=('Thickness proxies through-plane bandwidth loss; no wavelet module',9,'Eq. 13'),trainingCost=('100 epochs per stage on 8×A6000; APN frozen during stage 2',10,'Implementation'),inferenceCost=('APN plus 0–15 velocity NFEs; patch blending and volume assembly',10,'Implementation'),supervision=('HR scans to synthesize LR/HR pairs; input/target thickness at inference',6,'Secs. 3.1–3.2'),modality=('Brain T1w, T2w and FLAIR MRI',9,'Sec. 4.1'),datasets=('HCP, MIND, IDEAS; real in-house/fastMRI; CC359 scheduling analysis',9,'Sec. 4.1'),metrics=('PSNR, SSIM, LPIPS; latency and velocity NFEs',13,'Sec. 4.4')),
 questions=[q('Method','Why start stage 2 from APN output rather than noise?','Think distance to the target and neighboring slices.','APN provides coarse anatomy near the target and correlated deterministic initial states across neighboring slices. Stage 2 can focus on residual detail.',7,'Sec. 3.3'),q('Method','What is frozen during stage-2 training?','The initialization should not keep moving.','The stage-1 APN. The velocity model learns to refine its stable coarse prediction.',7,'Sec. 3.4'),q('Method','What does CETA align?','Two nearby acquisition conditions share the same anatomy.','Endpoint proxies z + v for two proximal thickness conditions generated from the same HR patch; the main gap is 1 mm.',8,'Sec. 3.5'),q('Reasoning','How does DRIFT differ from ParaFlow in accelerating inference?','Changing the problem versus parallelizing the solver.','DRIFT trains a shorter residual transport and chooses fewer sequential steps using metadata. ParaFlow keeps the pretrained vector field and iteratively evaluates tentative steps in parallel.',9,'Sec. 3.6'),q('Reasoning','If the input thickness equals the target, what does AIS prescribe?','PAD is 1 − Thr/Ti.','PAD = 0 and N = 0 in the reported setting. No velocity refinement is requested, but APN and the rest of the pipeline are not free.',9,'Eqs. 13–14')])
fig(p,'concept',4,'Figure 1',[132,112,484,276],'Fig. 1:','See the two reasons for fewer steps','Compare random-noise and APN initialization, then easy and hard acquisition conditions.','Initialization shortens the path; scheduling changes its numerical budget.')
fig(p,'architecture',5,'Figure 2',[132,112,484,335],'Fig. 2:','Separate the two training stages','Find the frozen APN, straight interpolation path, and proximal-thickness CETA pair.','CETA is a training constraint; it is not an additional inference network.',True)
fig(p,'efficiency',14,'Figure 6',[305,112,484,238],'Fig. 6:','Compare NFE and reconstruction quality','Compare DRIFT across ×2, ×6 and ×8; keep the axes and metric directions in mind.','A step budget is thickness-dependent, and velocity NFEs do not count the APN cost.')
finish(p)
p=dict(id='c2p',short='C2P',number='05',filename='ECCV26_05_C2P.pdf',title='Concept-to-Pixel: Prompt-Free Universal Medical Image Segmentation',category='Medical segmentation',task='Prompt-free multimodal segmentation',color='#87b9cb',position=[510,665],concepts=['segmentation','multimodal','geometry','dynamic','generalization','dice'],
 sentence=claim('Teach a segmenter separate concepts for shape and medical appearance, then let those concepts control how it draws each mask.',3,'Introduction'),
 problem=claim('Universal segmentation must cope with conflicting appearances across modalities. Prompt-based models require user input, reference-based models depend on support examples, and naive joint training can suffer negative transfer.',2,'Introduction'),
 core=[claim('Geometry tokens are supervised with measurable attributes extracted from masks, such as area and centroid. Semantic tokens are aligned with structured medical descriptions generated offline by an MLLM and encoded by PubMedBERT. Image-derived style and content modify only the semantic tokens.',5,'Sec. 2.2'),claim('Bidirectional cross-attention makes tokens and image features sample-specific. A token-guided dynamic head creates foreground/background convolution weights for each image. At inference, geometry-aware consensus compares predicted attributes against mask-derived geometry to weight augmented views.',6,'Sec. 2.2; consensus p. 8')],
 io=claim('A medical image enters; foreground/background masks come out. At inference there are no manual prompts, reference images, or new MLLM-generated reports; geometric consensus can use several perturbed views.',8,'Sec. 2.4; zero-shot setup p. 10'),
 why=claim('Shape provides a constraint shared across many modalities, while semantic tokens retain modality-dependent appearance. Explicit supervision makes these concept roles testable through ablations, but compact-shape priors can also fail on different topology.',11,'Generalization; Table 3 p. 12'),
 caution=claim('Prompt-free is not supervision-free. Mask-derived attributes and offline MLLM reports are training supervision. Geometry-aware consensus adds multiple-view inference, so it is not established sampling acceleration.',9,'Implementation; Table 3 p. 12'),
 novelty=[claim('Explicitly supervised geometry tokens and MLLM-distilled semantic tokens, with modality bias injected only into semantics.',5,'Sec. 2.2'),claim('Token-guided dynamic prediction conditioned on both token types and image context.',6,'Eqs. 6–7'),claim('Use agreement between regressed geometry and predicted-mask geometry as an inference reliability signal.',8,'Sec. 2.4')],
 existing=claim('ConvNeXt-based encoder–decoding, cross-attention, dynamic convolution, Qwen3-VL-Plus and PubMedBERT are ingredients. Their concept supervision and integration are the paper-specific design.',9,'Implementation; p. 6 Sec. 2.2'),
 stages=[stage('Image features','Medical image','Extract shallow E2 and deep E5 backbone features.','Provide appearance statistics and structural context.','Multiscale visual features',5,'Fig. 2','Trained'),stage('Geometry + semantics','Learned tokens and image features','SCFM injects style/content modality bias into semantic tokens only.','Keep a shared geometry pathway while adapting appearance concepts.','Geometry and modality-aware semantic tokens',5,'Sec. 2.2','Trained'),stage('Bidirectional interaction','Tokens and deep visual features','Tokens query images, then images query updated tokens.','Ground concepts in this particular input.','Instance-aware tokens and refined features',6,'Eqs. 2–5','Trained'),stage('Dynamic head','Aggregated token features and decoder context','Generate image-specific foreground/background convolution parameters.','Adapt the pixel classifier to the input.','Predicted masks',6,'Eqs. 6–7','Trained'),stage('Geometry consensus','Masks and regressed geometry from augmented views','Downweight views whose area/centroid disagree with their own geometry predictions.','Suppress internally inconsistent predictions.','Weighted final mask',8,'Sec. 2.4','Inference only')],
 training=[claim('Offline: derive nine geometric attributes from ground-truth masks. Generate structured reports with Qwen3-VL-Plus and encode them into fixed PubMedBERT targets.',9,'Implementation'),claim('Train the backbone, concept tokens, interactions and dynamic head with segmentation, geometry MSE, and semantic cosine-alignment losses.',7,'Sec. 2.3'),claim('Text embeddings are frozen supervision targets; the learned semantic tokens are optimized. The MLLM is an offline teacher.',28,'Appendix B; offline embeddings')],
 inference=[claim('Run the trained segmenter on the input image; no prompt, support example, or external MLLM call is required.',10,'Zero-shot evaluation'),claim('Use perturbed views and geometry self-consistency to weight and aggregate masks; near-zero area contradictions receive explicit suppression.',8,'Sec. 2.4')],
 results=[result('Average Dice (%)','Eight-dataset in-domain benchmark','Spider',87.32,88.22,'up',9,'Table 1','One unified model. C2P does not win every individual dataset: nnUNetV2 is higher on AMDSD and BTD.'),result('Dice (%)','Unseen Montgomery X-ray','Spider, 64 references',83.89,87.60,'up',11,'Table 2','C2P uses zero references; this is one unseen-modality result, not proof of universal transfer.'),result('Dice (%)','Unseen ISBI electron microscopy','SR-ICL',83.21,26.79,'up',11,'Table 2','A pronounced failure. The authors link it to a compact-shape prior conflicting with elongated neuronal topology.')],
 limitations=[claim('The compactness learned from macroscopic lesions transfers poorly to filamentous neuronal structures in electron microscopy.',11,'Table 2 & discussion','Authors’ failure analysis'),claim('The paper reports mixed zero-shot outcomes: C2P trails Spider on BUSBRA and nnUNetV2 on GlaS.',11,'Table 2','Scope of evidence'),claim('Geometry-aware consensus improves average Dice from 88.16 (standard TTA) to 88.22. This small incremental gain should be separated from the larger token-supervision gains.',12,'Table 3','Scope of evidence')],
 equations=[equation('Weight a view by geometric self-consistency',r'w_i=\exp\!\left[-\lambda\left(10|a_i^{\mathrm{reg}}-a_i^{\mathrm{px}}|+\|c_i^{\mathrm{reg}}-c_i^{\mathrm{px}}\|_2\right)\right]',['i: perturbed view; wi: its confidence weight','areg / creg: regressed area / centroid from geometry tokens','apx / cpx: area / centroid measured from the predicted mask','λ: penalty sharpness; exp: exponential; ‖·‖₂: Euclidean distance'],'A view gets less influence when its mask contradicts the geometry predicted by its own tokens.','This connects explicitly trained geometry tokens to an inference-time self-check. Internal consistency is not a guarantee of correctness.',8,'Eq. 13')],
 dimensions=[dim('generalization','Primary contribution','One model across seven training modalities; explicitly mixed zero-shot results.',11,'Table 2'),dim('medical','Application','Fully automatic medical image segmentation across diverse tasks.',9,'Table 1'),dim('data','Interaction reduction','No prompts or reference examples at inference. This does not establish fewer training labels.',10,'Zero-shot evaluation')],takeaway='Learn what a lesion looks like separately from its shape—but remember that a shape prior can be wrong.',
 comparison=compare(domain=('Universal medical segmentation',1,'Abstract'),architecture=('ConvNeXt-based backbone, GEO/SEM tokens, bidirectional cross-attention, TGDH',5,'Fig. 2; p. 9 Implementation'),objective=('Structure + Dice segmentation; geometric MSE; semantic cosine embedding loss',7,'Sec. 2.3'),generative=('Not a generative sampler; the MLLM provides offline training descriptions',9,'Implementation'),flow=('No flow/diffusion segmentation process',5,'Fig. 2'),frequency=('SCFM uses feature mean/std, not a wavelet decomposition',5,'SCFM'),trainingCost=('Offline Qwen reports and PubMedBERT targets; 50 epochs, batch 8',9,'Implementation'),inferenceCost=('Dynamic segmentation and augmented-view consensus; measured speedup not reported',8,'Sec. 2.4'),supervision=('Masks, mask-derived geometric properties, offline MLLM text embeddings',9,'Implementation'),modality=('Pathology, ultrasound, endoscopy, CT, dermoscopy, OCT, MRI; unseen X-ray/EM tests',9,'Table 1; Table 2 p. 11'),datasets=('EBHI, TNUI, BUSI, Polyp, COVID, ISIC2018, AMDSD, BTD; eight additional zero-shot datasets',8,'Sec. 3.1; p. 9'),metrics=('Dice (%)',9,'Table 1')),
 questions=[q('Method','How are geometry tokens different from semantic tokens?','Compare their supervision.','Geometry tokens regress attributes computed from masks. Semantic tokens align to MLLM-generated descriptions encoded by PubMedBERT; only semantics receives the modality embedding.',5,'Sec. 2.2'),q('Method','What makes the segmentation head dynamic?','Its weights depend on this image.','An MLP generates foreground/background convolution weights from aggregated geometric tokens, semantic tokens and global image context.',6,'Eq. 7'),q('Method','Is an MLLM consulted for each test image?','Distinguish the teacher from the student.','No. The semantic knowledge is distilled through offline training embeddings; no new reports, prompts or tokens are introduced at zero-shot inference.',10,'Zero-shot evaluation'),q('Reasoning','Why can geometry supervision hurt on electron microscopy?','Training topology matters.','The learned compactness prior fits many training lesions but conflicts with elongated neuronal structures. The paper reports only 26.79 Dice on ISBI EM.',11,'Table 2'),q('Reasoning','Is C2P’s annotation story the same as WCC4MS?','Training labels versus inference interaction.','No. C2P removes inference prompts/references while using masks and concept supervision during training. WCC4MS explicitly combines dense masks and cheaper boxes.',9,'Implementation')])
fig(p,'paradigms',2,'Figure 1',[32,32,383,211],'Fig. 1:','Locate C2P among segmentation paradigms','Separate manual prompts, reference images, and learned internal concepts.','Prompt-free deployment is a claim about interaction, not absence of training supervision.')
fig(p,'architecture',5,'Figure 2',[32,32,383,180],'Fig. 2:','Trace concepts into pixel predictions','Find SCFM, bidirectional attention, TGDH and the two supervision targets.','Geometry and semantics meet in the head, but have different training signals.',True)
fig(p,'consensus',8,'Figure 3',[182,110,382,210],'Fig. 3:','See inference-time reliability weighting','Compare mask-derived attributes against GEO predictions across flipped views.','Disagreement lowers a view’s weight; no ground-truth mask is consulted at inference.')
finish(p)

p=dict(id='paraflow',short='ParaFlow',number='06',filename='ECCV26_06_ParaFlow.pdf',title='ParaFlow: Parallel Sampling for Flow Matching Models',category='Inference efficiency',task='Parallel generative ODE sampling',color='#b8cc87',position=[510,105],concepts=['flow','ode','nfe','parallel','diffusion','latent'],
 sentence=claim('Generate faster by evaluating several tentative ODE steps in parallel, then iteratively correcting them to agree.',3,'Sec. 4'),
 problem=claim('An ordinary Euler sampler waits for each neural-vector-field evaluation before starting the next step. Even a strong pretrained flow model therefore has a long sequential latency chain.',3,'Sec. 3 & 4.1'),
 core=[claim('Unroll the discrete ODE trajectory into triangular nonlinear equations: each state must equal the initial state plus the accumulated earlier velocity increments. Given tentative states, all their expensive vector-field evaluations can be computed at once; a fixed-point update revises the guesses.',3,'Sec. 4.2'),claim('ParaFlow operates within a sliding window, accepting a contiguous prefix whose changes satisfy a tolerance and advancing to the next part of the trajectory. The vector field stays pretrained. Exact convergence recovers the sequential discretized trajectory; practical early stopping introduces a tolerance–quality trade-off.',4,'Secs. 4.3–4.4')],
 io=claim('Initial noise, prompt/model conditioning, a pretrained flow vector field, a time schedule, window size and tolerance enter the sampler. The terminal sampled state is decoded into an image by the existing model.',4,'Algorithm 1 & experimental setup'),
 why=claim('The triangular dependency means early states become correct first and remain correct. The full fixed-point scheme converges in at most N iterations; much smaller practical iteration counts are empirical, not guaranteed by that worst-case bound.',4,'Proposition 2; proof p. 12'),
 caution=claim('Fewer sequential iterations and lower wall-clock time do not mean fewer total NFEs. The experiments use eight Ascend 910B devices, and parallel-state storage also increases memory requirements.',4,'Experimental setup; limitations pp. 8–9'),
 novelty=[claim('Formulate flow-matching sampling as triangular nonlinear equations with a trajectory-equivalent root.',3,'Sec. 4.2'),claim('Use parallel fixed-point updates within a tolerance-controlled sliding window for pretrained FM models.',4,'Algorithm 1'),claim('Give trajectory-equivalence and finite-iteration convergence arguments, then measure latency, iterations, NFEs and quality separately.',4,'Proposition 2; Table 1 p. 5')],
 existing=claim('Pretrained SD3/Flux vector fields, Euler integration, fixed-point iteration, and prior diffusion parallel-sampling ideas are reused. The authors explicitly build on ParaDiGMS, ParaTAA and ParaSolver.',2,'Parallel sampling related work'),
 stages=[stage('Initialize window','Initial noise, schedule, tolerance δ and window p','Set tentative states for the first window to the initial noise.','Start the solver without training a new model.','Tentative trajectory states',4,'Algorithm 1','No training'),stage('Parallel evaluation','Tentative states at their respective times','Evaluate the frozen vector-field network at p times in parallel.','Replace a serial dependency chain with simultaneous expensive calls.','Window of velocity estimates',4,'Algorithm 1','Frozen pretrained model'),stage('Fixed-point correction','Window velocities','Accumulate time-weighted increments and update tentative states.','Make the trajectory better satisfy the original Euler equations.','Revised states',3,'Eqs. 4–6','Numerical solver'),stage('Accept and slide','Previous and revised states','Test per-state changes; accept a converged prefix and shift the window.','Avoid recomputing accepted states and bound working memory.','Next active window',4,'Sec. 4.4','Inference'),stage('Return sample','Converged terminal state','Use the existing model’s image decoding.','Finish generation without modifying the vector field.','Generated image',4,'Algorithm 1 & setup','Inference')],
 training=[claim('No new training, distillation, or fine-tuning is introduced by ParaFlow. Start with pretrained flow-matching models.',2,'Training-free description'),claim('The original model has already learned its vector field; that pretraining cost is outside the sampler contribution.',2,'Sec. 3')],
 inference=[claim('Draw initial noise; choose the existing schedule, tolerance and parallel window. Keep all pretrained weights fixed.',4,'Algorithm 1'),claim('Repeat parallel vector-field evaluation, prefix-sum state update, convergence check and sliding-window advance.',4,'Algorithm 1'),claim('Return the final state. Latency savings depend on available parallel hardware; memory and total evaluation cost can increase.',9,'Limitations continuation')],
 results=[result('Latency (s / image)','FluxPrompting, FLUX 512², 50-step schedule','Euler',23.80,5.58,'down',9,'Table 5','Window 8, tolerance 0.01, 10,000 prompts; eight Ascend 910B devices.'),result('Total NFEs','Same FLUX 512² setting','Euler',50,123.51,'down',9,'Table 5','Higher computational workload accompanies the latency gain.'),result('FID','Same FLUX 512² setting','Euler',52.66,52.58,'down',9,'Table 5','Quality is close in this setting. This small difference is not a claim of significant superiority.'),result('FID','SD3 1024², 100-step schedule','Euler',50.75,51.62,'down',5,'Table 1','A quality cost in another setting; ParaFlow’s practical tolerance is not exact convergence.')],
 limitations=[claim('Parallel resources are required for speedups and intermediate-state memory increases. The current implementation is not fully system-optimized.',9,'Sec. 6 continuation','Authors’ limitation'),claim('Exact-trajectory theory concerns convergence to the chosen discrete sampler. Early stopping by tolerance can change image metrics; it does not remove ODE discretization error.',4,'Propositions 1–2; Table 2 p. 6','Reading boundary')],
 equations=[equation('Solve the trajectory together',r'\hat x_{t_i}^{(k+1)}=x_{t_0}+\sum_{j=0}^{i-1}h_j\,v(\hat x_{t_j}^{(k)},t_j,\theta)',['x at t₀: initial noise; x̂ at ti: tentative state at schedule time ti','k: fixed-point iteration; i,j: schedule indices','hj = tj+1 − tj: step size; v: pretrained vector field; θ: fixed parameters','The t₀ state stays fixed in every iteration.'],'Use the old guesses to evaluate every velocity concurrently, then accumulate them into new guesses.','This expands Eqs. 5–6 into one expression. Parallelism applies to network evaluations; consistency emerges over successive iterations.',3,'Eqs. 5–6 (Eq. 6 on p. 4)')],
 dimensions=[dim('inference','Primary contribution','Lower sequential latency through parallel evaluations; total NFEs can increase.',9,'Table 5'),dim('training','Avoided additional training','Training-free sampler for pretrained models, not a reduction of original model training cost.',2,'Training-free description')],takeaway='Less waiting can require more work: latency, iteration count and total NFEs are different quantities.',
 comparison=compare(domain=('Text-to-image generative sampling',4,'Experimental setup'),architecture=('Unchanged SD3 / FLUX models; a parallel numerical sampler',4,'Sec. 5'),objective=('No new training objective',2,'Training-free description'),generative=('Pretrained flow-matching ODE',2,'Sec. 3'),flow=('Parallel fixed-point solve of Euler trajectory equations',3,'Sec. 4'),frequency=('No wavelet/frequency intervention',3,'Sec. 4'),trainingCost=('No extra training or distillation; pretrained-model cost excluded',2,'Training-free description'),inferenceCost=('Trades higher total NFEs and memory for lower latency; tested on 8 Ascend 910B devices',4,'Sec. 5; p. 9 limitations'),supervision=('No extra training supervision; existing text conditioning',4,'Sec. 5'),modality=('Natural-image generation, not a medical experiment',4,'Sec. 5'),datasets=('10,000 random FluxPrompting prompts',4,'Sec. 5'),metrics=('Iterations, total NFEs, latency, FID and CLIP score',5,'Table 1')),
 questions=[q('Method','What exactly does ParaFlow parallelize?','Each tentative state already has a guessed value.','Vector-field evaluations at different tentative time states, within a sliding window. Fixed-point iterations then reconcile the trajectory.',4,'Algorithm 1'),q('Method','What happens to the model weights?','This is a solver contribution.','They remain pretrained and fixed. No new loss, distillation or fine-tuning is introduced.',2,'Training-free description'),q('Method','What is the theoretical convergence guarantee?','Separate worst-case iterations from observed speed.','The full fixed-point scheme recovers the same sequential discrete trajectory in at most N iterations. Fewer practical iterations are observed; tolerance-based stopping is approximate.',4,'Proposition 2'),q('Reasoning','How can latency decrease while total NFEs increase?','Several calls finish simultaneously.','Many vector-field evaluations are performed concurrently. For FLUX 512², 50-step Euler takes 23.80 s and 50 NFEs, while window-8 ParaFlow takes 5.58 s and 123.51 NFEs.',9,'Table 5'),q('Reasoning','Would the reported speedup automatically hold on one small GPU?','Check hardware and memory requirements.','No. Parallel capacity and intermediate-state memory are essential. The reported experiments used eight Ascend 910B devices.',4,'Sec. 5; p. 9 limitations')])
fig(p,'algorithm',4,'Algorithm 1',[105,84,507,264],'Algorithm 1:','Follow the actual sampler','Find the parallel velocity evaluation, convergence stride, and window update.','This PDF contains an algorithm rather than a main architecture figure; it is the authoritative method visual.',True)
fig(p,'progression',6,'Figure 1',[105,90,507,249],'Figure 1:','Compare progress per sequential iteration','Read top as Euler and bottom as ParaFlow at the labelled iteration counts.','At an equal iteration index, ParaFlow may have done more total model evaluations.')
fig(p,'window',9,'Table 5',[105,82,507,203],'Table 5:','Expose the latency/compute trade-off','Track window size, iterations, NFE and time together.','A larger parallel window does not monotonically improve measured latency; window 8 is best among these settings.')
finish(p)
p=dict(id='debat',short='DeBaT',number='07',filename='ECCV26_07_DeBaT.pdf',title='Decoupling High and Low Frequencies for Faithful Image Generation with Fine Details',category='Representation efficiency',task='Detail-preserving latent image generation',color='#d7a28b',position=[100,385],concepts=['wavelets','frequency','latent','diffusion','fid'],
 sentence=claim('Give coarse structure and fine detail separate encoders and losses, then combine their latents for image generation.',7,'Fig. 3'),
 problem=claim('A tokenizer can improve overall reconstruction while still losing textures, sharp edges, and text. Joint objectives tend to favor dominant low-frequency structure, so extra latent capacity alone does not resolve the frequency imbalance.',2,'Introduction'),
 core=[claim('A single Haar wavelet decomposition splits the input into a low-frequency LL band and high-frequency LH/HL/HH bands. Separate encoder–decoder pairs learn these groups independently. The low branch uses VA-VAE-style objectives, including foundation alignment; the high branch omits pretrained-model supervision.',8,'Sec. 3.2; high-frequency objective p. 9'),claim('The resulting low/high latents are concatenated along channels for LightningDiT training. Generation samples a joint learned latent, splits its channels, decodes the two frequency groups, and uses the inverse wavelet transform to reconstruct an image. The main total latent size matches VA-VAE: 16 × 16 × 32.',9,'Sec. 3.3; latent size p. 8')],
 io=claim('Tokenizer reconstruction maps an input image through two band-specific latents back to an image. Generation starts from the latent generative model, then uses the two trained decoders and inverse Haar transform; no source image is required for synthesis.',9,'Inference & Sec. 3.3'),
 why=claim('Separate optimization prevents dominant low-frequency errors from competing with high-frequency detail learning inside one shared tokenizer objective. Coupled-wavelet ablations test whether simply using wavelets is sufficient.',14,'Table 3 & frequency-decoupling ablation'),
 caution=claim('The generator models learned, concatenated latent embeddings—not raw wavelet coefficients. Better fidelity at equal latent size does not mean a smaller or faster tokenizer: parameters and latency are higher than VA-VAE in Table 5.',15,'Table 5; fusion p. 9'),
 novelty=[claim('Evaluate reconstruction separately in low and high frequency bands to expose a detail-preservation bottleneck.',6,'Sec. 3.1'),claim('Learn independent band-specific VAEs with different supervision before fusing the latents.',8,'Sec. 3.2'),claim('Integrate the concatenated band latents into an existing latent generative pipeline at matched total latent dimensionality.',9,'Sec. 3.3')],
 existing=claim('Haar wavelets, VAE/KL training, adversarial objectives, DINOv2 alignment, and LightningDiT are existing components. Frequency decomposition alone is not DeBaT’s novelty; independent representation learning is.',8,'Sec. 3.2'),
 stages=[stage('Haar decomposition','RGB image','Split once into LL and the LH/HL/HH detail bands; normalize components.','Expose structure and detail as separate learning problems.','Low-frequency and high-frequency inputs',8,'Sec. 3.2','Fixed transform'),stage('Separate encoders','Normalized low/high bands','Encode each group with a dedicated VAE encoder.','Avoid a fully coupled band representation.','zL and zH',8,'Sec. 3.2','Trained'),stage('Latent fusion','zL and zH','Concatenate along channels for the generative model.','Keep one joint generation interface at a matched latent size.','16 × 16 × 32 combined latent',9,'Sec. 3.3','Representation'),stage('Band decoding','Reconstructed or generated split latents','Decode low and high groups with their respective decoders.','Turn each learned representation back into its frequency components.','Reconstructed LL and detail bands',9,'Inference','Trained'),stage('Inverse Haar','Reconstructed frequency groups','Apply inverse wavelet transform.','Combine coarse structure and fine details in image space.','Reconstructed or generated image',10,'Sec. 3.3','Fixed transform')],
 training=[claim('Train the low-band VAE with reconstruction, KL, vision-foundation alignment, adversarial and perceptual terms.',8,'Low-frequency objective'),claim('Train the high-band VAE with reconstruction, KL and adversarial terms, without pretrained-model supervision.',9,'High-frequency objective'),claim('Then train LightningDiT on concatenated learned latents. The tokenizer and generative-model stages serve different objectives.',12,'Sec. 4.2')],
 inference=[claim('For synthesis, sample the joint latent with the trained LightningDiT model, then split its channels into low/high groups.',9,'Sec. 3.3'),claim('Use both band decoders and inverse Haar reconstruction. The input-image encoders and training discriminators are not needed for synthesis.',9,'Inference & Sec. 3.3')],
 results=[result('High-frequency error','ImageNet-1K reconstruction, 50k validation images','VA-VAE',0.0074,0.0020,'down',11,'Table 1','Matched 16 × 16 × 32 latent size; this is reconstruction, not generation FID.'),result('gFID with CFG','ImageNet, LightningDiT, 64 epochs / 675M','VA-VAE tokenizer',2.11,1.52,'down',12,'Table 2','A controlled tokenizer comparison. REPA reports 1.42 in the same table at 800 epochs, so DeBaT is not the best value in every row.'),result('Tokenizer latency (ms/image)','256², batch size 32','VA-VAE',17.29,19.97,'down',15,'Table 5','Fidelity improves while tokenizer speed worsens against VA-VAE; DeBaT also uses 137.91M vs 72.60M parameters.')],
 limitations=[claim('The current model uses one decomposition stage and focuses on a VA-VAE foundation; multi-stage and other tokenizer integrations are future work.',15,'Discussion & future direction','Authors’ limitation'),claim('Dual encoder–decoder branches increase parameter count, and latency is higher than VA-VAE in the reported setup.',15,'Table 5','Measured trade-off'),claim('Table 3 reports DeBaT rFID 0.4156 while Table 1 reports 0.2156. These are separate table contexts; the atlas does not treat them as one interchangeable score.',14,'Table 3; Table 1 p. 11','Source qualification')],
 equations=[equation('Decode bands, then reconstruct the image',r'\hat{\mathbf x}_L=D_L(\mathbf z_L),\quad\hat{\mathbf x}_H=D_H(\mathbf z_H),\quad\hat{\mathbf x}=\mathcal W^{-1}(\hat{\mathbf x}_L,\hat{\mathbf x}_H)',['zL / zH: low/high learned latent codes (encoded or sampled)','DL / DH: independently trained band decoders','x̂L / x̂H: reconstructed low/high bands; x̂: final image','W⁻¹: inverse Haar discrete wavelet transform'],'Decode each part into the frequency group it learned, then recombine the groups with a fixed inverse transform.','The separation lives inside the tokenizer; the diffusion model samples the concatenated learned latents.',9,'Sec. 3.2, unnumbered inference equation')],
 dimensions=[dim('representation','Primary contribution','More faithful detail at matched total latent dimensionality.',11,'Table 1'),dim('backbone','Added cost','137.91M tokenizer parameters versus 72.60M for VA-VAE; not an architectural size reduction.',15,'Table 5'),dim('inference','Trade-off','Better reconstruction, but 19.97 vs 17.29 ms/image against VA-VAE.',15,'Table 5')],takeaway='Wavelets expose the bands; separate learning protects the details.',
 comparison=compare(domain=('Natural-image tokenization and generation',1,'Abstract'),architecture=('Two band-specific VAE encoder–decoder pairs, channel fusion, LightningDiT',7,'Fig. 3'),objective=('Low: reconstruction/KL/GAN/foundation/perceptual; high: reconstruction/KL/GAN',8,'Sec. 3.2; p. 9'),generative=('LightningDiT operating on concatenated learned latents',9,'Sec. 3.3'),flow=('Integrated into the paper’s latent diffusion pipeline; no new sampler',9,'Sec. 3.3'),frequency=('Single-stage Haar: LL versus LH/HL/HH; independent optimization',8,'Sec. 3.2'),trainingCost=('Two VAEs plus generative-model training; no demonstrated reduction against VA-VAE',15,'Table 5'),inferenceCost=('Two decoders and inverse Haar; tokenizer latency 19.97 ms/image at batch 32',15,'Table 5'),supervision=('Images; low branch uses pretrained feature alignment; high branch omits it',8,'Sec. 3.2'),modality=('Natural RGB images; no medical evaluation',10,'Experiments'),datasets=('ImageNet-1K; FFHQ 1024² extension',10,'Sec. 4; Table 4 p. 14'),metrics=('Band reconstruction error, PSNR, LPIPS, rFID; gFID/sFID, IS, precision/recall',11,'Tables 1–2')),
 questions=[q('Method','Why use different losses for the two frequency groups?','The high branch avoids pretrained-feature bias.','The low branch uses semantic/foundation and perceptual supervision. The high branch uses reconstruction, KL and adversarial terms without pretrained-model supervision to focus on fine details.',9,'High-frequency objective'),q('Method','Does LightningDiT generate raw wavelet coefficients?','Locate the latent fusion step.','No. It models the concatenated learned low/high latent codes. Separate decoders produce the bands afterwards.',9,'Sec. 3.3'),q('Method','What makes this more than adding Haar DWT to a VAE?','Follow where learning becomes separate.','Dedicated encoder–decoder pairs and independent objectives decouple band optimization. Coupled wavelet-input baselines are tested separately.',14,'Table 3'),q('Reasoning','How is DeBaT’s use of wavelets different from KernelWave?','Representation versus training augmentation.','DeBaT learns separate compressed band representations for reconstruction and generation. KernelWave scales high-frequency coefficients to create smooth/sharp training variants for segmentation.',8,'Sec. 3.2'),q('Reasoning','Does better fidelity at equal latent size imply lower inference cost?','Check the parameter and timing columns.','No. DeBaT has more parameters and higher tokenizer latency than VA-VAE in Table 5 despite better reconstruction.',15,'Table 5')])
fig(p,'designs',5,'Figure 2',[132,112,484,261],'Fig. 2:','Distinguish wavelet tokenizer designs','Compare shared latent codes with DeBaT’s independently learned bands.','The central difference is decoupled optimization, not simply the presence of a wavelet transform.')
fig(p,'architecture',7,'Figure 3',[132,112,484,236],'Fig. 3:','Trace the frequency-aware latent pathway','Follow low/high encoders, distinct losses, fused latents and separate decoders.','The learned latents, not raw bands, form the generative model’s representation.',True)
fig(p,'errors',11,'Figure 4',[132,374,484,560],'Fig. 4:','Look for where detail is lost','Inspect the error maps around faces, patterned clothing and printed text.','These examples explain the band-error metrics; they do not independently establish all generation claims.')
finish(p)

p=dict(id='wcc4ms',short='WCC4MS',number='08',filename='ECCV26_08_WCC4MS3DSeg.pdf',title='Wavelet-Driven Cross-Domain Consistency for Mixed-Supervised 3D Tumor Segmentation',category='Data & annotation efficiency',task='Mixed-supervised 3D tumor segmentation',color='#d7a28b',position=[100,665],concepts=['wavelets','frequency','segmentation','weak','generalization','dice','hd95'],
 sentence=claim('Use masks and cheaper boxes together, while training the segmenter to stay consistent across synthetic smooth and sharp scans.',1,'Abstract'),
 problem=claim('Dense 3D tumor masks are expensive. Adding box-labelled scans helps only if their different reconstruction characteristics do not confuse the model; mixing supervision from different sources can introduce harmful domain shifts.',2,'Introduction'),
 core=[claim('KernelWave decomposes a 3D patch using Haar wavelets. It keeps the low-frequency component and scales high-frequency coefficients up or down to create sharp and smooth variants. This approximates reconstruction-kernel frequency changes without requiring raw metadata.',6,'Sec. 3.2; implementation p. 9'),claim('The dual-branch system routes each sample to mask or box supervision through task-specific decoding. Consistency between the variants and an auxiliary domain-classification objective train useful features across domains. Deployment uses only the segmentation branch on candidate-centered patches.',7,'Sec. 3.3; implementation p. 9')],
 io=claim('Training uses lesion-centered 3D patches with either voxel masks or bounding boxes plus dataset identity. Inference uses a patch around an already localized candidate lesion and returns a tumor mask.',9,'Sec. 4.2'),
 why=claim('The smooth/sharp pair changes frequency emphasis while keeping the lesion anatomy aligned. Consistency discourages brittle responses to those changes; cheap boxes supply localization information, while masks preserve boundary supervision.',5,'Fig. 2; ablation p. 13','Method rationale'),
 caution=claim('KernelWave is a metadata-free frequency proxy, not an exact CT reconstruction simulator. The domain head predicts provenance; it is not an adversarial domain-invariance module.',14,'Mechanism validation; p. 8 domain loss'),
 novelty=[claim('Combine KernelWave frequency variants with mixed mask/box supervision in a lesion-centered 3D framework.',5,'Fig. 2'),claim('Enforce output consistency across smooth/sharp views while routing available annotation types to task-specific losses.',7,'Sec. 3.3'),claim('Use a domain-aware auxiliary head to retain task-relevant image-quality cues.',8,'Domain-classification discussion')],
 existing=claim('Haar DWT, 3D U-Net/UNETR backbones, mask and detection losses, and KL consistency are established machinery. Their joint use for reconstruction-related shifts under mixed supervision is the contribution.',7,'Sec. 3.3; implementation p. 9'),
 stages=[stage('Candidate patch','Localized lesion with mask or box annotation','Crop a 96³ CT patch centered on the annotated candidate.','Focus on lesion segmentation after localization.','Lesion-centered patch',9,'Sec. 4.2','Localization prerequisite'),stage('KernelWave','3D patch','Apply two-level Haar decomposition; scale detail coefficients by δ and 1/δ.','Create smooth/sharp frequency variants of the same anatomy.','Aligned paired image variants',6,'Eqs. 4–6; p. 9','Training augmentation'),stage('Task-specific decoding','Features from the paired branches','Use the available mask or bounding-box supervision.','Exploit both annotation types without treating a box as a dense mask.','Segmentation or detection predictions',7,'Sec. 3.3','Training'),stage('Consistency + domain head','Paired predictions and source-domain labels','Apply KL consistency and predict dataset identity alongside task losses.','Learn robustness while retaining useful domain/quality cues.','Jointly optimized features',8,'Eq. 11','Training only'),stage('Segmentation deployment','Candidate-centered test patch','Use only the trained segmentation branch.','Discard auxiliary supervision machinery at deployment.','Voxelwise tumor mask',9,'Sec. 4.2','Inference')],
 training=[claim('Combine mask-labelled CT data and box-only PN9; use 96³ candidate-centered patches and Haar KernelWave variants.',9,'Sec. 4.2'),claim('Route labels to Dice segmentation or detection classification/regression losses. Jointly add KL consistency and domain classification.',7,'Sec. 3.3; p. 8 Eq. 11'),claim('The domain head is a predictive auxiliary regularizer, not an adversarial mechanism that erases domain information.',8,'Domain-classification discussion')],
 inference=[claim('Assume first-stage candidate localization has already happened. Crop a lesion-centered patch; this is not an end-to-end whole-scan detector.',9,'Sec. 4.2'),claim('Use only the segmentation branch. Box decoding, domain-supervision losses, and KernelWave paired training views are not required by the reported deployment path.',9,'Sec. 4.2; Fig. 2 p. 5')],
 results=[result('DSC (%)','LIDC-IDRI, 3D U-Net, mask:box 1:2','MixSegNet',78.19,80.32,'up',9,'Table 1','Compare mixed-supervision baselines under the same reported setting, not full data versus fewer labels.'),result('Average DSC (%)','Leave-one-domain-out CT evaluation','GTVSeg',57.93,59.88,'up',11,'Table 3','Average over LIDC-IDRI, MSD-Lung and LNDb; absolute out-of-domain scores remain much lower than in-domain scores.'),result('HD95','MSD-Lung, 3D UNETR','MIST',8.13,8.21,'down',10,'Table 2','A counter-result: WCC4MS is slightly worse on this boundary metric despite its higher DSC.')],
 limitations=[claim('The pipeline assumes candidate localization and evaluates patches centered on annotations. Whole-scan localization performance is outside the demonstrated segmentation result.',9,'Sec. 4.2','Scope of evidence'),claim('Too much weak box supervision can harm fine boundary learning; performance drops as the box share grows beyond a moderate ratio.',12,'Ratio discussion; Fig. 4 p. 13','Observed limitation'),claim('Frequency modulation approximates a dominant kernel effect but is not an exact reconstruction simulation.',14,'Mechanism validation','Authors’ qualification')],
 equations=[equation('Make the same anatomy smoother or sharper',r'\widetilde{\mathcal X}_{\epsilon}^{(v)}=\delta\mathcal X_{\epsilon}^{(v)}\quad\text{(sharp)},\qquad\widetilde{\mathcal X}_{\epsilon}^{(v)}=\frac{1}{\delta}\mathcal X_{\epsilon}^{(v)}\quad\text{(smooth)}',['Xε(v): detail coefficients at wavelet level v','ε: one of LLH, LHL, HLL, LHH, HLH, HHL, HHH','δ > 1: gain; the reported best gain is 4','X̃: modified coefficients; the low-frequency LLL component is unchanged'],'Turn up or down the detail bands while retaining the coarse structure, then reconstruct a spatial image.','These paired training variants expose the segmenter to frequency shifts without acquisition metadata. The wavelet coefficients are not learned latent tokens.',6,'Eqs. 4–6')],
 dimensions=[dim('data','Primary contribution','Combine a limited mask set with cheaper bounding boxes.',9,'Table 1'),dim('generalization','Primary contribution','Frequency variants and consistency for cross-domain CT segmentation.',11,'Table 3'),dim('medical','Application','Lesion-centered 3D tumor segmentation, primarily lung CT; MRI extension also reported.',11,'Cross-modality validation')],takeaway='Cheap labels help when their domains are handled carefully; wavelets create training variation here.',
 comparison=compare(domain=('Mixed-supervised 3D tumor segmentation',1,'Abstract'),architecture=('3D U-Net or UNETR; paired branches, task-specific mask/box decoding, domain heads',5,'Fig. 2; Tables 1–2'),objective=('Dice + detection classification/regression + KL consistency + domain classification',8,'Eq. 11'),generative=('Not a generative model',5,'Fig. 2'),flow=('No flow/diffusion sampler',5,'Fig. 2'),frequency=('Two-level 3D Haar; HF gain δ or 1/δ; LF unchanged',6,'Sec. 3.2; p. 9 implementation'),trainingCost=('Auxiliary branches and frequency augmentation; 80 epochs, batch 8, 2×RTX 4090',8,'Sec. 4.2; continuation p. 9'),inferenceCost=('Segmentation branch only on candidate-centered patches; speedup not reported',9,'Sec. 4.2'),supervision=('Masks + bounding boxes + dataset/domain identity',7,'Sec. 3.3'),modality=('Primary lung CT; brain MRI extension',11,'Cross-modality validation'),datasets=('LIDC-IDRI, MSD-Lung, LNDb; box-only PN9; MRI: BraTS, MSD-BT, FeTS, TCGA-GBM',8,'Sec. 4.1; p. 11'),metrics=('DSC (%), HD95; frequency validation uses RKPN separately',9,'Table 1; Table 8 p. 14')),
 questions=[q('Method','What does KernelWave change and what does it preserve?','Separate high and low frequency bands.','It scales the high-frequency coefficients by δ or 1/δ and leaves the low-frequency component unchanged before inverse reconstruction.',6,'Eqs. 4–6'),q('Method','Which branch is used at deployment?','Look past the crowded training figure.','Only the segmentation branch. The box branch provides training supervision, and candidate localization is assumed to have happened already.',9,'Sec. 4.2'),q('Method','Does the domain head erase domain information adversarially?','Check the objective’s direction.','No. It predicts dataset provenance and encourages domain/quality-aware features constrained by the task and consistency losses.',8,'Domain-classification discussion'),q('Reasoning','Why can adding more bounding boxes eventually hurt?','Cheap localization is not a precise boundary.','Excessive box supervision can divert attention from fine boundary textures. The reported ratio study improves at a moderate box share but degrades at higher shares.',12,'Ratio discussion'),q('Reasoning','Why are shared wavelets insufficient to call this the same idea as DeBaT?','Ask what is trained on the bands.','Here wavelet modulation creates spatial training images for robustness. DeBaT learns separate compressed band representations for generation.',6,'Sec. 3.2')])
fig(p,'motivation',2,'Figure 1',[132,112,484,374],'Fig. 1:','Understand the label/domain interaction','Compare aligned and misaligned weak-label additions and the unseen-domain diagram.','The motivation is joint annotation efficiency and domain robustness, not merely a larger dataset.')
fig(p,'architecture',5,'Figure 2',[132,112,484,321],'Fig. 2:','Trace augmentation and annotation routing','Follow smooth/sharp variants into the mask/box supervision branches and auxiliary losses.','The crowded training diagram is larger than the deployment path, which retains only segmentation.',True)
fig(p,'ratios',13,'Figure 4',[166,253,454,430],'Fig. 4:','See why more weak labels is not always better','Follow the peak and subsequent decline as box share increases.','There is an annotation-balance trade-off; abundant boxes do not replace precise boundaries.')
finish(p)

# Keep comparison inputs and outputs distinct rather than repeating the I/O overview.
contracts={
 'transferability':('Generation: text prompt. Understanding: image and question.','Generated image or textual answer, depending on the task.'),
 'sphere':('Reconstructed MRI; recovered DVF supplied to the segmentation network after preprocessing.','Brain tumor-region masks.'),
 'pdf':('Baseline MRI, baseline lesion mask and desired time interval.','Predicted lesion evolution and a forecast future MRI.'),
 'drift':('Thick-slice MRI, input slice thickness and target thickness.','A super-resolved MRI volume assembled from refined patches/slices.'),
 'c2p':('A medical image; multiple perturbed views for consensus. No user prompt or reference image.','Foreground/background segmentation masks, aggregated using predicted geometry.'),
 'paraflow':('Initial noise, pretrained conditioned vector field, time schedule, tolerance and window size.','Terminal sampled state, decoded by the existing model into an image.'),
 'debat':('Reconstruction: an RGB image. Synthesis: latent generator sampling and class conditioning.','An RGB image reconstructed by separate low/high-band decoders and inverse Haar.'),
 'wcc4ms':('A candidate-centered 3D patch after lesion localization.','Voxelwise tumor segmentation from the segmentation branch.')
}
for p in papers:
 for key,text in zip(['input','output'],contracts[p['id']]):
  p['comparison'][key]=claim(text,p['io']['source']['page'],p['io']['source']['label'])

(ROOT/'data/papers.json').write_text(json.dumps(papers,ensure_ascii=False,indent=2)+'\n')
(ROOT/'data/figure-crops.json').write_text(json.dumps(crops,ensure_ascii=False,indent=2)+'\n')
print(f'Authored {len(papers)} papers, {sum(len(p["questions"]) for p in papers)} questions, {len(crops)} source crops.')
